// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft2DKernel_streamingDataCommutor_complex_ap_fixed_30_16_5_3_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        fftOutData_local_dout,
        fftOutData_local_empty_n,
        fftOutData_local_read,
        fftOutData_local2_din,
        fftOutData_local2_full_n,
        fftOutData_local2_write,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] fftOutData_local_dout;
input   fftOutData_local_empty_n;
output   fftOutData_local_read;
output  [255:0] fftOutData_local2_din;
input   fftOutData_local2_full_n;
output   fftOutData_local2_write;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fftOutData_local_read;
reg fftOutData_local2_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln231_fu_441_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire   [0:0] fifo_has_next_sample_nbreadreq_fu_156_p3;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg   [0:0] delay_line_stall_load_reg_985;
reg   [0:0] delay_line_stall_load_reg_985_pp0_iter1_reg;
reg   [0:0] and_ln297_2_reg_1073;
reg   [0:0] fifo_has_next_sample_reg_976;
reg   [0:0] fifo_has_next_sample_reg_976_pp0_iter1_reg;
reg    ap_predicate_op112_write_state4;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [1:0] control_count_V;
reg   [1:0] control_bits_V;
reg   [1:0] sample_in_read_count_V;
reg   [0:0] delay_line_stall;
reg    delayline_Array_1_ce0;
reg    delayline_Array_1_we0;
wire   [60:0] delayline_Array_1_q0;
reg    delayline_Array_11_ce0;
reg    delayline_Array_11_we0;
wire   [60:0] delayline_Array_11_q0;
reg    delayline_Array_36_ce0;
reg    delayline_Array_36_we0;
wire   [60:0] delayline_Array_36_q0;
reg    control_delayline_Array_ce0;
reg    control_delayline_Array_we0;
wire   [31:0] control_delayline_Array_q0;
reg    control_delayline_Array_6_ce0;
reg    control_delayline_Array_6_we0;
wire   [31:0] control_delayline_Array_6_q0;
reg    control_delayline_Array_21_ce0;
reg    control_delayline_Array_21_we0;
wire   [31:0] control_delayline_Array_21_q0;
reg    delayline_Array_ce0;
reg    delayline_Array_we0;
wire   [60:0] delayline_Array_q0;
reg    delayline_Array_45_ce0;
reg    delayline_Array_45_we0;
wire   [60:0] delayline_Array_45_q0;
reg    delayline_Array_25_ce0;
reg    delayline_Array_25_we0;
wire   [60:0] delayline_Array_25_q0;
reg    fftOutData_local_blk_n;
wire    ap_block_pp0_stage0;
reg    fftOutData_local2_blk_n;
reg   [3:0] t59_reg_192;
wire   [3:0] t_fu_307_p2;
reg   [3:0] t_reg_980;
wire   [0:0] delay_line_stall_load_load_fu_313_p1;
wire   [29:0] temp_tagged_input_triangle_delay_input_sample_M_real_V_0_fu_317_p1;
reg   [0:0] icmp_ln231_reg_1029;
reg   [0:0] icmp_ln231_reg_1029_pp0_iter1_reg;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_real_V_3_fu_757_p6;
reg   [29:0] temp_tagged_output_triangle_input_sample_M_real_V_3_reg_1033;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p6;
reg   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_3_reg_1038;
wire   [29:0] commuted_output_sample_M_real_V_0_fu_819_p1;
reg   [29:0] commuted_output_sample_M_real_V_0_reg_1043;
reg   [29:0] commuted_output_sample_M_imag_V_0_reg_1048;
wire   [29:0] commuted_output_sample_M_real_V_1_fu_861_p1;
reg   [29:0] commuted_output_sample_M_real_V_1_reg_1053;
reg   [29:0] commuted_output_sample_M_imag_V_1_reg_1058;
wire   [29:0] commuted_output_sample_M_real_V_2_fu_903_p1;
reg   [29:0] commuted_output_sample_M_real_V_2_reg_1063;
reg   [29:0] commuted_output_sample_M_imag_V_2_reg_1068;
wire   [0:0] and_ln297_2_fu_937_p2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg   [3:0] ap_phi_mux_t59_phi_fu_196_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_valid_0_reg_206;
reg   [0:0] ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206;
wire   [29:0] ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_3_0_reg_219;
reg   [29:0] ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_3_0_reg_219;
wire   [29:0] ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_2_0_reg_230;
reg   [29:0] ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_2_0_reg_230;
wire   [29:0] ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_1_0_reg_241;
reg   [29:0] ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_1_0_reg_241;
wire   [29:0] ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252;
reg   [29:0] ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252;
wire   [29:0] ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_3_0_reg_263;
reg   [29:0] ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_3_0_reg_263;
wire   [29:0] ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_2_0_reg_274;
reg   [29:0] ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_2_0_reg_274;
wire   [29:0] ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_1_0_reg_285;
reg   [29:0] ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_1_0_reg_285;
wire   [29:0] ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296;
reg   [29:0] ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296;
wire   [1:0] add_ln870_fu_401_p2;
wire   [1:0] add_ln870_1_fu_417_p2;
wire   [0:0] icmp_ln256_fu_423_p2;
reg    ap_block_pp0_stage0_01001;
wire   [60:0] p_03_i_fu_447_p4;
wire   [60:0] p_04_i_fu_489_p4;
wire   [60:0] p_05_i_fu_531_p4;
wire   [31:0] zext_ln66_fu_577_p1;
wire   [31:0] zext_ln66_1_fu_637_p1;
wire   [31:0] zext_ln66_2_fu_697_p1;
wire   [60:0] p_i1_fu_799_p4;
wire   [60:0] p_2_i_fu_841_p4;
wire   [60:0] p_4_i_fu_883_p4;
wire   [29:0] temp_tagged_mux_chain_input_sample_M_real_V_1_fu_551_p1;
wire   [29:0] temp_tagged_mux_chain_input_sample_M_real_V_2_fu_509_p1;
wire   [29:0] temp_tagged_mux_chain_input_sample_M_real_V_3_fu_467_p1;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p2;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p3;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p4;
wire   [0:0] temp_tagged_output_triangle_input_valid_0_fu_619_p2;
wire   [0:0] temp_tagged_output_triangle_input_valid_0_fu_619_p3;
wire   [0:0] temp_tagged_output_triangle_input_valid_0_fu_619_p4;
wire   [1:0] trunc_ln316_fu_633_p1;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p2;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p3;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p4;
wire   [0:0] temp_tagged_output_triangle_input_valid_1_fu_679_p2;
wire   [0:0] temp_tagged_output_triangle_input_valid_1_fu_679_p3;
wire   [0:0] temp_tagged_output_triangle_input_valid_1_fu_679_p4;
wire   [1:0] trunc_ln316_2_fu_693_p1;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p2;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p3;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p4;
wire   [0:0] temp_tagged_output_triangle_input_valid_2_fu_739_p2;
wire   [0:0] temp_tagged_output_triangle_input_valid_2_fu_739_p3;
wire   [0:0] temp_tagged_output_triangle_input_valid_2_fu_739_p4;
wire   [1:0] trunc_ln79_fu_753_p1;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p2;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p3;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p4;
wire   [0:0] temp_tagged_output_triangle_input_valid_3_fu_785_p2;
wire   [0:0] temp_tagged_output_triangle_input_valid_3_fu_785_p3;
wire   [0:0] temp_tagged_output_triangle_input_valid_3_fu_785_p4;
wire   [0:0] temp_tagged_output_triangle_input_valid_0_fu_619_p6;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p6;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_real_V_0_fu_591_p6;
wire   [0:0] temp_tagged_output_triangle_input_valid_1_fu_679_p6;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p6;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_real_V_1_fu_651_p6;
wire   [0:0] temp_tagged_output_triangle_input_valid_2_fu_739_p6;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p6;
wire   [29:0] temp_tagged_output_triangle_input_sample_M_real_V_2_fu_711_p6;
wire   [0:0] commuted_output_valid_0_fu_833_p3;
wire   [0:0] commuted_output_valid_1_fu_875_p3;
wire   [0:0] commuted_output_valid_2_fu_917_p3;
wire   [0:0] temp_tagged_output_triangle_input_valid_3_fu_785_p6;
wire   [0:0] and_ln297_1_fu_931_p2;
wire   [0:0] and_ln297_fu_925_p2;
wire   [253:0] tmp_fu_943_p16;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_int_blocking_cur_n;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_259;
reg    ap_condition_77;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 control_count_V = 2'd0;
#0 control_bits_V = 2'd0;
#0 sample_in_read_count_V = 2'd0;
#0 delay_line_stall = 1'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

fft2DKernel_streamingDataCommutor_complex_ap_fixed_30_16_5_3_0_s_delayline_Array_1 #(
    .DataWidth( 61 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
delayline_Array_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd2),
    .ce0(delayline_Array_1_ce0),
    .we0(delayline_Array_1_we0),
    .d0(p_03_i_fu_447_p4),
    .q0(delayline_Array_1_q0)
);

fft2DKernel_streamingDataCommutor_complex_ap_fixed_30_16_5_3_0_s_delayline_Array_11 #(
    .DataWidth( 61 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
delayline_Array_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(delayline_Array_11_ce0),
    .we0(delayline_Array_11_we0),
    .d0(p_04_i_fu_489_p4),
    .q0(delayline_Array_11_q0)
);

fft2DKernel_streamingDataCommutor_complex_ap_fixed_30_16_5_3_0_s_delayline_Array_36 #(
    .DataWidth( 61 ),
    .AddressRange( 1 ),
    .AddressWidth( 1 ))
delayline_Array_36_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd0),
    .ce0(delayline_Array_36_ce0),
    .we0(delayline_Array_36_we0),
    .d0(p_05_i_fu_531_p4),
    .q0(delayline_Array_36_q0)
);

fft2DKernel_streamingDataCommutor_complex_ap_fixed_22_8_5_3_0_s_control_delayline_Array_17 #(
    .DataWidth( 32 ),
    .AddressRange( 1 ),
    .AddressWidth( 1 ))
control_delayline_Array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd0),
    .ce0(control_delayline_Array_ce0),
    .we0(control_delayline_Array_we0),
    .d0(zext_ln66_fu_577_p1),
    .q0(control_delayline_Array_q0)
);

fft2DKernel_streamingDataCommutor_complex_ap_fixed_22_8_5_3_0_s_control_delayline_Array_17 #(
    .DataWidth( 32 ),
    .AddressRange( 1 ),
    .AddressWidth( 1 ))
control_delayline_Array_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd0),
    .ce0(control_delayline_Array_6_ce0),
    .we0(control_delayline_Array_6_we0),
    .d0(zext_ln66_1_fu_637_p1),
    .q0(control_delayline_Array_6_q0)
);

fft2DKernel_streamingDataCommutor_complex_ap_fixed_22_8_5_3_0_s_control_delayline_Array_17 #(
    .DataWidth( 32 ),
    .AddressRange( 1 ),
    .AddressWidth( 1 ))
control_delayline_Array_21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd0),
    .ce0(control_delayline_Array_21_ce0),
    .we0(control_delayline_Array_21_we0),
    .d0(zext_ln66_2_fu_697_p1),
    .q0(control_delayline_Array_21_q0)
);

fft2DKernel_streamingDataCommutor_complex_ap_fixed_30_16_5_3_0_s_delayline_Array_1 #(
    .DataWidth( 61 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
delayline_Array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd2),
    .ce0(delayline_Array_ce0),
    .we0(delayline_Array_we0),
    .d0(p_i1_fu_799_p4),
    .q0(delayline_Array_q0)
);

fft2DKernel_streamingDataCommutor_complex_ap_fixed_30_16_5_3_0_s_delayline_Array_11 #(
    .DataWidth( 61 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
delayline_Array_45_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(delayline_Array_45_ce0),
    .we0(delayline_Array_45_we0),
    .d0(p_2_i_fu_841_p4),
    .q0(delayline_Array_45_q0)
);

fft2DKernel_streamingDataCommutor_complex_ap_fixed_30_16_5_3_0_s_delayline_Array_36 #(
    .DataWidth( 61 ),
    .AddressRange( 1 ),
    .AddressWidth( 1 ))
delayline_Array_25_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd0),
    .ce0(delayline_Array_25_ce0),
    .we0(delayline_Array_25_we0),
    .d0(p_4_i_fu_883_p4),
    .q0(delayline_Array_25_q0)
);

fft2DKernel_mux_42_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 30 ))
mux_42_30_1_1_U1045(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296),
    .din1(temp_tagged_mux_chain_input_sample_M_real_V_1_fu_551_p1),
    .din2(temp_tagged_mux_chain_input_sample_M_real_V_2_fu_509_p1),
    .din3(temp_tagged_mux_chain_input_sample_M_real_V_3_fu_467_p1),
    .din4(control_bits_V),
    .dout(temp_tagged_output_triangle_input_sample_M_real_V_0_fu_591_p6)
);

fft2DKernel_mux_42_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 30 ))
mux_42_30_1_1_U1046(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252),
    .din1(temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p2),
    .din2(temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p3),
    .din3(temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p4),
    .din4(control_bits_V),
    .dout(temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p6)
);

fft2DKernel_mux_42_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
mux_42_1_1_1_U1047(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206),
    .din1(temp_tagged_output_triangle_input_valid_0_fu_619_p2),
    .din2(temp_tagged_output_triangle_input_valid_0_fu_619_p3),
    .din3(temp_tagged_output_triangle_input_valid_0_fu_619_p4),
    .din4(control_bits_V),
    .dout(temp_tagged_output_triangle_input_valid_0_fu_619_p6)
);

fft2DKernel_mux_42_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 30 ))
mux_42_30_1_1_U1048(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296),
    .din1(temp_tagged_mux_chain_input_sample_M_real_V_1_fu_551_p1),
    .din2(temp_tagged_mux_chain_input_sample_M_real_V_2_fu_509_p1),
    .din3(temp_tagged_mux_chain_input_sample_M_real_V_3_fu_467_p1),
    .din4(trunc_ln316_fu_633_p1),
    .dout(temp_tagged_output_triangle_input_sample_M_real_V_1_fu_651_p6)
);

fft2DKernel_mux_42_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 30 ))
mux_42_30_1_1_U1049(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252),
    .din1(temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p2),
    .din2(temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p3),
    .din3(temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p4),
    .din4(trunc_ln316_fu_633_p1),
    .dout(temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p6)
);

fft2DKernel_mux_42_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
mux_42_1_1_1_U1050(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206),
    .din1(temp_tagged_output_triangle_input_valid_1_fu_679_p2),
    .din2(temp_tagged_output_triangle_input_valid_1_fu_679_p3),
    .din3(temp_tagged_output_triangle_input_valid_1_fu_679_p4),
    .din4(trunc_ln316_fu_633_p1),
    .dout(temp_tagged_output_triangle_input_valid_1_fu_679_p6)
);

fft2DKernel_mux_42_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 30 ))
mux_42_30_1_1_U1051(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296),
    .din1(temp_tagged_mux_chain_input_sample_M_real_V_1_fu_551_p1),
    .din2(temp_tagged_mux_chain_input_sample_M_real_V_2_fu_509_p1),
    .din3(temp_tagged_mux_chain_input_sample_M_real_V_3_fu_467_p1),
    .din4(trunc_ln316_2_fu_693_p1),
    .dout(temp_tagged_output_triangle_input_sample_M_real_V_2_fu_711_p6)
);

fft2DKernel_mux_42_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 30 ))
mux_42_30_1_1_U1052(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252),
    .din1(temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p2),
    .din2(temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p3),
    .din3(temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p4),
    .din4(trunc_ln316_2_fu_693_p1),
    .dout(temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p6)
);

fft2DKernel_mux_42_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
mux_42_1_1_1_U1053(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206),
    .din1(temp_tagged_output_triangle_input_valid_2_fu_739_p2),
    .din2(temp_tagged_output_triangle_input_valid_2_fu_739_p3),
    .din3(temp_tagged_output_triangle_input_valid_2_fu_739_p4),
    .din4(trunc_ln316_2_fu_693_p1),
    .dout(temp_tagged_output_triangle_input_valid_2_fu_739_p6)
);

fft2DKernel_mux_42_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 30 ))
mux_42_30_1_1_U1054(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296),
    .din1(temp_tagged_mux_chain_input_sample_M_real_V_1_fu_551_p1),
    .din2(temp_tagged_mux_chain_input_sample_M_real_V_2_fu_509_p1),
    .din3(temp_tagged_mux_chain_input_sample_M_real_V_3_fu_467_p1),
    .din4(trunc_ln79_fu_753_p1),
    .dout(temp_tagged_output_triangle_input_sample_M_real_V_3_fu_757_p6)
);

fft2DKernel_mux_42_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .din2_WIDTH( 30 ),
    .din3_WIDTH( 30 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 30 ))
mux_42_30_1_1_U1055(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252),
    .din1(temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p2),
    .din2(temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p3),
    .din3(temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p4),
    .din4(trunc_ln79_fu_753_p1),
    .dout(temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p6)
);

fft2DKernel_mux_42_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
mux_42_1_1_1_U1056(
    .din0(ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206),
    .din1(temp_tagged_output_triangle_input_valid_3_fu_785_p2),
    .din2(temp_tagged_output_triangle_input_valid_3_fu_785_p3),
    .din3(temp_tagged_output_triangle_input_valid_3_fu_785_p4),
    .din4(trunc_ln79_fu_753_p1),
    .dout(temp_tagged_output_triangle_input_valid_3_fu_785_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln231_reg_1029_pp0_iter1_reg == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_1_0_reg_241 <= 30'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_1_0_reg_241 <= {{fftOutData_local_dout[125:96]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_1_0_reg_241 <= ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_1_0_reg_241;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_2_0_reg_230 <= 30'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_2_0_reg_230 <= {{fftOutData_local_dout[189:160]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_2_0_reg_230 <= ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_2_0_reg_230;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_3_0_reg_219 <= 30'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_3_0_reg_219 <= {{fftOutData_local_dout[253:224]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_3_0_reg_219 <= ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_3_0_reg_219;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_1_0_reg_285 <= 30'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_1_0_reg_285 <= {{fftOutData_local_dout[93:64]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_1_0_reg_285 <= ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_1_0_reg_285;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_2_0_reg_274 <= 30'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_2_0_reg_274 <= {{fftOutData_local_dout[157:128]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_2_0_reg_274 <= ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_2_0_reg_274;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_3_0_reg_263 <= 30'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_3_0_reg_263 <= {{fftOutData_local_dout[221:192]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_3_0_reg_263 <= ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_3_0_reg_263;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252 <= 30'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252 <= {{fftOutData_local_dout[61:32]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252 <= ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296 <= 30'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296 <= temp_tagged_input_triangle_delay_input_sample_M_real_V_0_fu_317_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296 <= ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        if (((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (delay_line_stall_load_load_fu_313_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206 <= 1'd0;
        end else if ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206 <= ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_valid_0_reg_206;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln231_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t59_reg_192 <= t_reg_980;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln231_reg_1029 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        t59_reg_192 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        and_ln297_2_reg_1073 <= and_ln297_2_fu_937_p2;
        commuted_output_sample_M_imag_V_0_reg_1048 <= {{delayline_Array_q0[59:30]}};
        commuted_output_sample_M_imag_V_1_reg_1058 <= {{delayline_Array_45_q0[59:30]}};
        commuted_output_sample_M_imag_V_2_reg_1068 <= {{delayline_Array_25_q0[59:30]}};
        commuted_output_sample_M_real_V_0_reg_1043 <= commuted_output_sample_M_real_V_0_fu_819_p1;
        commuted_output_sample_M_real_V_1_reg_1053 <= commuted_output_sample_M_real_V_1_fu_861_p1;
        commuted_output_sample_M_real_V_2_reg_1063 <= commuted_output_sample_M_real_V_2_fu_903_p1;
        temp_tagged_output_triangle_input_sample_M_imag_V_3_reg_1038 <= temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p6;
        temp_tagged_output_triangle_input_sample_M_real_V_3_reg_1033 <= temp_tagged_output_triangle_input_sample_M_real_V_3_fu_757_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        control_bits_V <= control_count_V;
        control_count_V <= add_ln870_fu_401_p2;
        delay_line_stall <= icmp_ln256_fu_423_p2;
        sample_in_read_count_V <= add_ln870_1_fu_417_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        delay_line_stall_load_reg_985 <= delay_line_stall;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        delay_line_stall_load_reg_985_pp0_iter1_reg <= delay_line_stall_load_reg_985;
        fifo_has_next_sample_reg_976 <= fifo_has_next_sample_nbreadreq_fu_156_p3;
        fifo_has_next_sample_reg_976_pp0_iter1_reg <= fifo_has_next_sample_reg_976;
        icmp_ln231_reg_1029 <= icmp_ln231_fu_441_p2;
        icmp_ln231_reg_1029_pp0_iter1_reg <= icmp_ln231_reg_1029;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_reg_980 <= t_fu_307_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln231_reg_1029_pp0_iter1_reg == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_259)) begin
        if ((icmp_ln231_reg_1029 == 1'd1)) begin
            ap_phi_mux_t59_phi_fu_196_p6 = 4'd0;
        end else if ((icmp_ln231_reg_1029 == 1'd0)) begin
            ap_phi_mux_t59_phi_fu_196_p6 = t_reg_980;
        end else begin
            ap_phi_mux_t59_phi_fu_196_p6 = t59_reg_192;
        end
    end else begin
        ap_phi_mux_t59_phi_fu_196_p6 = t59_reg_192;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (icmp_ln231_fu_441_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        control_delayline_Array_21_ce0 = 1'd1;
    end else begin
        control_delayline_Array_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        control_delayline_Array_21_we0 = 1'd1;
    end else begin
        control_delayline_Array_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        control_delayline_Array_6_ce0 = 1'd1;
    end else begin
        control_delayline_Array_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        control_delayline_Array_6_we0 = 1'd1;
    end else begin
        control_delayline_Array_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        control_delayline_Array_ce0 = 1'd1;
    end else begin
        control_delayline_Array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        control_delayline_Array_we0 = 1'd1;
    end else begin
        control_delayline_Array_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_11_ce0 = 1'd1;
    end else begin
        delayline_Array_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_11_we0 = 1'd1;
    end else begin
        delayline_Array_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_1_ce0 = 1'd1;
    end else begin
        delayline_Array_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_1_we0 = 1'd1;
    end else begin
        delayline_Array_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_25_ce0 = 1'd1;
    end else begin
        delayline_Array_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_25_we0 = 1'd1;
    end else begin
        delayline_Array_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_36_ce0 = 1'd1;
    end else begin
        delayline_Array_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_36_we0 = 1'd1;
    end else begin
        delayline_Array_36_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_45_ce0 = 1'd1;
    end else begin
        delayline_Array_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_45_we0 = 1'd1;
    end else begin
        delayline_Array_45_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_ce0 = 1'd1;
    end else begin
        delayline_Array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((fifo_has_next_sample_reg_976 == 1'd1) | (delay_line_stall_load_reg_985 == 1'd0)))) begin
        delayline_Array_we0 = 1'd1;
    end else begin
        delayline_Array_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op112_write_state4 == 1'b1))) begin
        fftOutData_local2_blk_n = fftOutData_local2_full_n;
    end else begin
        fftOutData_local2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op112_write_state4 == 1'b1))) begin
        fftOutData_local2_write = 1'b1;
    end else begin
        fftOutData_local2_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fftOutData_local_blk_n = fftOutData_local_empty_n;
    end else begin
        fftOutData_local_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fftOutData_local_read = 1'b1;
    end else begin
        fftOutData_local_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln870_1_fu_417_p2 = (sample_in_read_count_V + 2'd1);

assign add_ln870_fu_401_p2 = (control_count_V + 2'd1);

assign and_ln297_1_fu_931_p2 = (temp_tagged_output_triangle_input_valid_3_fu_785_p6 & commuted_output_valid_2_fu_917_p3);

assign and_ln297_2_fu_937_p2 = (and_ln297_fu_925_p2 & and_ln297_1_fu_931_p2);

assign and_ln297_fu_925_p2 = (commuted_output_valid_1_fu_875_p3 & commuted_output_valid_0_fu_833_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op112_write_state4 == 1'b1) & (fftOutData_local2_full_n == 1'b0)) | ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1) & (fftOutData_local_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op112_write_state4 == 1'b1) & (fftOutData_local2_full_n == 1'b0)) | ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1) & (fftOutData_local_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op112_write_state4 == 1'b1) & (fftOutData_local2_full_n == 1'b0)) | ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1) & (fftOutData_local_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((fifo_has_next_sample_nbreadreq_fu_156_p3 == 1'd1) & (fftOutData_local_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((ap_predicate_op112_write_state4 == 1'b1) & (fftOutData_local2_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_259 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_77 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_ext_blocking_n = (1'b1 & 1'b1);

assign ap_int_blocking_cur_n = (fftOutData_local_blk_n & fftOutData_local2_blk_n);

assign ap_int_blocking_n = (ap_int_blocking_cur_n & 1'b1);

assign ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_1_0_reg_241 = 'bx;

assign ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_2_0_reg_230 = 'bx;

assign ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_imag_V_3_0_reg_219 = 'bx;

assign ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_1_0_reg_285 = 'bx;

assign ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_2_0_reg_274 = 'bx;

assign ap_phi_reg_pp0_iter0_temp_tagged_input_triangle_delay_input_sample_M_real_V_3_0_reg_263 = 'bx;

assign ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_imag_V_0_reg_252 = 'bx;

assign ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_sample_M_real_V_0_reg_296 = 'bx;

assign ap_phi_reg_pp0_iter0_temp_tagged_mux_chain_input_valid_0_reg_206 = 'bx;

always @ (*) begin
    ap_predicate_op112_write_state4 = (((fifo_has_next_sample_reg_976_pp0_iter1_reg == 1'd1) & (1'd1 == and_ln297_2_reg_1073)) | ((delay_line_stall_load_reg_985_pp0_iter1_reg == 1'd0) & (1'd1 == and_ln297_2_reg_1073)));
end

assign ap_str_blocking_n = (1'b1 & 1'b1);

assign commuted_output_sample_M_real_V_0_fu_819_p1 = delayline_Array_q0[29:0];

assign commuted_output_sample_M_real_V_1_fu_861_p1 = delayline_Array_45_q0[29:0];

assign commuted_output_sample_M_real_V_2_fu_903_p1 = delayline_Array_25_q0[29:0];

assign commuted_output_valid_0_fu_833_p3 = delayline_Array_q0[32'd60];

assign commuted_output_valid_1_fu_875_p3 = delayline_Array_45_q0[32'd60];

assign commuted_output_valid_2_fu_917_p3 = delayline_Array_25_q0[32'd60];

assign delay_line_stall_load_load_fu_313_p1 = delay_line_stall;

assign fftOutData_local2_din = tmp_fu_943_p16;

assign fifo_has_next_sample_nbreadreq_fu_156_p3 = fftOutData_local_empty_n;

assign icmp_ln231_fu_441_p2 = ((ap_phi_mux_t59_phi_fu_196_p6 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_423_p2 = ((sample_in_read_count_V != 2'd3) ? 1'b1 : 1'b0);

assign p_03_i_fu_447_p4 = {{{ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206}, {ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_3_0_reg_219}}, {ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_3_0_reg_263}};

assign p_04_i_fu_489_p4 = {{{ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206}, {ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_2_0_reg_230}}, {ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_2_0_reg_274}};

assign p_05_i_fu_531_p4 = {{{ap_phi_reg_pp0_iter1_temp_tagged_mux_chain_input_valid_0_reg_206}, {ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_imag_V_1_0_reg_241}}, {ap_phi_reg_pp0_iter1_temp_tagged_input_triangle_delay_input_sample_M_real_V_1_0_reg_285}};

assign p_2_i_fu_841_p4 = {{{temp_tagged_output_triangle_input_valid_1_fu_679_p6}, {temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p6}}, {temp_tagged_output_triangle_input_sample_M_real_V_1_fu_651_p6}};

assign p_4_i_fu_883_p4 = {{{temp_tagged_output_triangle_input_valid_2_fu_739_p6}, {temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p6}}, {temp_tagged_output_triangle_input_sample_M_real_V_2_fu_711_p6}};

assign p_i1_fu_799_p4 = {{{temp_tagged_output_triangle_input_valid_0_fu_619_p6}, {temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p6}}, {temp_tagged_output_triangle_input_sample_M_real_V_0_fu_591_p6}};

assign t_fu_307_p2 = (ap_phi_mux_t59_phi_fu_196_p6 + 4'd1);

assign temp_tagged_input_triangle_delay_input_sample_M_real_V_0_fu_317_p1 = fftOutData_local_dout[29:0];

assign temp_tagged_mux_chain_input_sample_M_real_V_1_fu_551_p1 = delayline_Array_36_q0[29:0];

assign temp_tagged_mux_chain_input_sample_M_real_V_2_fu_509_p1 = delayline_Array_11_q0[29:0];

assign temp_tagged_mux_chain_input_sample_M_real_V_3_fu_467_p1 = delayline_Array_1_q0[29:0];

assign temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p2 = {{delayline_Array_36_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p3 = {{delayline_Array_11_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_0_fu_605_p4 = {{delayline_Array_1_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p2 = {{delayline_Array_36_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p3 = {{delayline_Array_11_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_1_fu_665_p4 = {{delayline_Array_1_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p2 = {{delayline_Array_36_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p3 = {{delayline_Array_11_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_2_fu_725_p4 = {{delayline_Array_1_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p2 = {{delayline_Array_36_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p3 = {{delayline_Array_11_q0[59:30]}};

assign temp_tagged_output_triangle_input_sample_M_imag_V_3_fu_771_p4 = {{delayline_Array_1_q0[59:30]}};

assign temp_tagged_output_triangle_input_valid_0_fu_619_p2 = delayline_Array_36_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_0_fu_619_p3 = delayline_Array_11_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_0_fu_619_p4 = delayline_Array_1_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_1_fu_679_p2 = delayline_Array_36_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_1_fu_679_p3 = delayline_Array_11_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_1_fu_679_p4 = delayline_Array_1_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_2_fu_739_p2 = delayline_Array_36_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_2_fu_739_p3 = delayline_Array_11_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_2_fu_739_p4 = delayline_Array_1_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_3_fu_785_p2 = delayline_Array_36_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_3_fu_785_p3 = delayline_Array_11_q0[32'd60];

assign temp_tagged_output_triangle_input_valid_3_fu_785_p4 = delayline_Array_1_q0[32'd60];

assign tmp_fu_943_p16 = {{{{{{{{{{{{{{{temp_tagged_output_triangle_input_sample_M_imag_V_3_reg_1038}, {2'd0}}, {temp_tagged_output_triangle_input_sample_M_real_V_3_reg_1033}}, {2'd0}}, {commuted_output_sample_M_imag_V_2_reg_1068}}, {2'd0}}, {commuted_output_sample_M_real_V_2_reg_1063}}, {2'd0}}, {commuted_output_sample_M_imag_V_1_reg_1058}}, {2'd0}}, {commuted_output_sample_M_real_V_1_reg_1053}}, {2'd0}}, {commuted_output_sample_M_imag_V_0_reg_1048}}, {2'd0}}, {commuted_output_sample_M_real_V_0_reg_1043}};

assign trunc_ln316_2_fu_693_p1 = control_delayline_Array_6_q0[1:0];

assign trunc_ln316_fu_633_p1 = control_delayline_Array_q0[1:0];

assign trunc_ln79_fu_753_p1 = control_delayline_Array_21_q0[1:0];

assign zext_ln66_1_fu_637_p1 = trunc_ln316_fu_633_p1;

assign zext_ln66_2_fu_697_p1 = trunc_ln316_2_fu_693_p1;

assign zext_ln66_fu_577_p1 = control_bits_V;

endmodule //fft2DKernel_streamingDataCommutor_complex_ap_fixed_30_16_5_3_0_s
