-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft2DKernel_cacheDataDR_16_4_ap_fixed_27_13_5_3_0_ap_fixed_27_13_5_3_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_inData_0_0_0_0_0_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    p_inData_0_0_0_0_0_empty_n : IN STD_LOGIC;
    p_inData_0_0_0_0_0_read : OUT STD_LOGIC;
    p_inData_0_1_0_0_0_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    p_inData_0_1_0_0_0_empty_n : IN STD_LOGIC;
    p_inData_0_1_0_0_0_read : OUT STD_LOGIC;
    p_inData_0_0_0_0_01_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    p_inData_0_0_0_0_01_empty_n : IN STD_LOGIC;
    p_inData_0_0_0_0_01_read : OUT STD_LOGIC;
    p_inData_0_1_0_0_04_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    p_inData_0_1_0_0_04_empty_n : IN STD_LOGIC;
    p_inData_0_1_0_0_04_read : OUT STD_LOGIC;
    p_inData_0_0_0_0_02_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    p_inData_0_0_0_0_02_empty_n : IN STD_LOGIC;
    p_inData_0_0_0_0_02_read : OUT STD_LOGIC;
    p_inData_0_1_0_0_05_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    p_inData_0_1_0_0_05_empty_n : IN STD_LOGIC;
    p_inData_0_1_0_0_05_read : OUT STD_LOGIC;
    p_inData_0_0_0_0_03_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    p_inData_0_0_0_0_03_empty_n : IN STD_LOGIC;
    p_inData_0_0_0_0_03_read : OUT STD_LOGIC;
    p_inData_0_1_0_0_06_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    p_inData_0_1_0_0_06_empty_n : IN STD_LOGIC;
    p_inData_0_1_0_0_06_read : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_digitReseversedOutputBuff_M_real_ce0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real_we0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real_d0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    p_digitReseversedOutputBuff_M_real7_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_digitReseversedOutputBuff_M_real7_ce0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real7_we0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real7_d0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    p_digitReseversedOutputBuff_M_real8_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_digitReseversedOutputBuff_M_real8_ce0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real8_we0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real8_d0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    p_digitReseversedOutputBuff_M_real9_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_digitReseversedOutputBuff_M_real9_ce0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real9_we0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_real9_d0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    p_digitReseversedOutputBuff_M_imag_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_digitReseversedOutputBuff_M_imag_ce0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_imag_we0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_imag_d0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    p_digitReseversedOutputBuff_M_imag10_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_digitReseversedOutputBuff_M_imag10_ce0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_imag10_we0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_imag10_d0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    p_digitReseversedOutputBuff_M_imag11_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_digitReseversedOutputBuff_M_imag11_ce0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_imag11_we0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_imag11_d0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    p_digitReseversedOutputBuff_M_imag12_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    p_digitReseversedOutputBuff_M_imag12_ce0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_imag12_we0 : OUT STD_LOGIC;
    p_digitReseversedOutputBuff_M_imag12_d0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    ap_ext_blocking_n : OUT STD_LOGIC;
    ap_str_blocking_n : OUT STD_LOGIC;
    ap_int_blocking_n : OUT STD_LOGIC );
end;


architecture behav of fft2DKernel_cacheDataDR_16_4_ap_fixed_27_13_5_3_0_ap_fixed_27_13_5_3_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln171_fu_806_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal io_acc_block_signal_op28 : STD_LOGIC;
    signal io_acc_block_signal_op32 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal io_acc_block_signal_op83 : STD_LOGIC;
    signal io_acc_block_signal_op102 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_inData_0_0_0_0_0_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_inData_0_0_0_0_01_blk_n : STD_LOGIC;
    signal p_inData_0_0_0_0_02_blk_n : STD_LOGIC;
    signal p_inData_0_0_0_0_03_blk_n : STD_LOGIC;
    signal p_inData_0_1_0_0_0_blk_n : STD_LOGIC;
    signal p_inData_0_1_0_0_04_blk_n : STD_LOGIC;
    signal p_inData_0_1_0_0_05_blk_n : STD_LOGIC;
    signal p_inData_0_1_0_0_06_blk_n : STD_LOGIC;
    signal r53_reg_265 : STD_LOGIC_VECTOR (1 downto 0);
    signal r53_reg_265_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal temp_M_real_V_3_4_reg_640 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_real_V_2_4_reg_658 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_real_V_1_4_reg_676 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_real_V_0_4_reg_694 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_3_4_reg_712 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_2_4_reg_730 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_1_4_reg_748 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_0_4_reg_766 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_real_V_0_reg_1000 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_0_reg_1008 : STD_LOGIC_VECTOR (26 downto 0);
    signal r_fu_792_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_reg_1016 : STD_LOGIC_VECTOR (1 downto 0);
    signal temp_M_real_V_0_10_reg_1021 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_0_10_reg_1029 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln171_reg_1037 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln171_reg_1037_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln184_fu_860_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_phi_mux_r53_phi_fu_269_p6 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_temp_M_real_V_3_1_phi_fu_283_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_3_1_reg_280 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_2_1_phi_fu_296_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_2_1_reg_293 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_1_1_phi_fu_309_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_1_1_reg_306 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_0_1_phi_fu_322_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_0_1_reg_319 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_3_1_phi_fu_335_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_3_1_reg_332 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_2_1_phi_fu_348_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_2_1_reg_345 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_1_1_phi_fu_361_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_1_1_reg_358 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_0_1_phi_fu_374_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_0_1_reg_371 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_3_2_phi_fu_387_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_3_2_reg_384 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_2_2_phi_fu_403_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_2_2_reg_400 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_1_2_phi_fu_419_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_1_2_reg_416 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_0_2_phi_fu_435_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_0_2_reg_432 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_3_2_phi_fu_451_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_3_2_reg_448 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_2_2_phi_fu_467_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_2_2_reg_464 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_1_2_phi_fu_483_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_1_2_reg_480 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_0_2_phi_fu_499_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_0_2_reg_496 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_3_3_phi_fu_515_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_3_3_reg_512 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_2_3_phi_fu_531_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_2_3_reg_528 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_1_3_phi_fu_547_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_1_3_reg_544 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_0_3_phi_fu_563_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_0_3_reg_560 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_3_3_phi_fu_579_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_3_3_reg_576 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_2_3_phi_fu_595_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_2_3_reg_592 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_1_3_phi_fu_611_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_1_3_reg_608 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_0_3_phi_fu_627_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_0_3_reg_624 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_3_4_phi_fu_644_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_3_4_reg_640 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_2_4_phi_fu_662_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_2_4_reg_658 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_1_4_phi_fu_680_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_1_4_reg_676 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_real_V_0_4_phi_fu_698_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_real_V_0_4_reg_694 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_3_4_phi_fu_716_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_3_4_reg_712 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_2_4_phi_fu_734_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_2_4_reg_730 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_1_4_phi_fu_752_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_1_4_reg_748 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_mux_temp_M_imag_V_0_4_phi_fu_770_p8 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_phi_reg_pp0_iter1_temp_M_imag_V_0_4_reg_766 : STD_LOGIC_VECTOR (26 downto 0);
    signal zext_ln171_fu_938_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal temp_M_imag_V_3_fu_82 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_3_22_fu_86 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_3_23_fu_90 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_imag_V_3_24_fu_94 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_real_V_3_fu_98 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_real_V_3_22_fu_102 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_real_V_3_23_fu_106 : STD_LOGIC_VECTOR (26 downto 0);
    signal temp_M_real_V_3_24_fu_110 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_int_blocking_cur_n : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_157 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    r53_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln171_reg_1037 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                r53_reg_265 <= r_reg_1016;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln171_reg_1037 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                r53_reg_265 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    temp_M_imag_V_0_4_reg_766_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_1))) then 
                temp_M_imag_V_0_4_reg_766 <= p_inData_0_1_0_0_06_dout;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_3)))) then 
                temp_M_imag_V_0_4_reg_766 <= ap_phi_mux_temp_M_imag_V_0_3_phi_fu_627_p8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                temp_M_imag_V_0_4_reg_766 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_0_4_reg_766;
            end if; 
        end if;
    end process;

    temp_M_imag_V_1_4_reg_748_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_2))) then 
                temp_M_imag_V_1_4_reg_748 <= p_inData_0_1_0_0_06_dout;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_3)))) then 
                temp_M_imag_V_1_4_reg_748 <= ap_phi_mux_temp_M_imag_V_1_3_phi_fu_611_p8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                temp_M_imag_V_1_4_reg_748 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_1_4_reg_748;
            end if; 
        end if;
    end process;

    temp_M_imag_V_2_4_reg_730_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_3))) then 
                temp_M_imag_V_2_4_reg_730 <= p_inData_0_1_0_0_06_dout;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_2)))) then 
                temp_M_imag_V_2_4_reg_730 <= ap_phi_mux_temp_M_imag_V_2_3_phi_fu_595_p8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                temp_M_imag_V_2_4_reg_730 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_2_4_reg_730;
            end if; 
        end if;
    end process;

    temp_M_imag_V_3_4_reg_712_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_3)))) then 
                temp_M_imag_V_3_4_reg_712 <= ap_phi_mux_temp_M_imag_V_3_3_phi_fu_579_p8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_0))) then 
                temp_M_imag_V_3_4_reg_712 <= p_inData_0_1_0_0_06_dout;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                temp_M_imag_V_3_4_reg_712 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_3_4_reg_712;
            end if; 
        end if;
    end process;

    temp_M_real_V_0_4_reg_694_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_1))) then 
                temp_M_real_V_0_4_reg_694 <= p_inData_0_0_0_0_03_dout;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_3)))) then 
                temp_M_real_V_0_4_reg_694 <= ap_phi_mux_temp_M_real_V_0_3_phi_fu_563_p8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                temp_M_real_V_0_4_reg_694 <= ap_phi_reg_pp0_iter1_temp_M_real_V_0_4_reg_694;
            end if; 
        end if;
    end process;

    temp_M_real_V_1_4_reg_676_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_2))) then 
                temp_M_real_V_1_4_reg_676 <= p_inData_0_0_0_0_03_dout;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_3)))) then 
                temp_M_real_V_1_4_reg_676 <= ap_phi_mux_temp_M_real_V_1_3_phi_fu_547_p8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                temp_M_real_V_1_4_reg_676 <= ap_phi_reg_pp0_iter1_temp_M_real_V_1_4_reg_676;
            end if; 
        end if;
    end process;

    temp_M_real_V_2_4_reg_658_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_3))) then 
                temp_M_real_V_2_4_reg_658 <= p_inData_0_0_0_0_03_dout;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_2)))) then 
                temp_M_real_V_2_4_reg_658 <= ap_phi_mux_temp_M_real_V_2_3_phi_fu_531_p8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                temp_M_real_V_2_4_reg_658 <= ap_phi_reg_pp0_iter1_temp_M_real_V_2_4_reg_658;
            end if; 
        end if;
    end process;

    temp_M_real_V_3_4_reg_640_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_3)))) then 
                temp_M_real_V_3_4_reg_640 <= ap_phi_mux_temp_M_real_V_3_3_phi_fu_515_p8;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (r53_reg_265 = ap_const_lv2_0))) then 
                temp_M_real_V_3_4_reg_640 <= p_inData_0_0_0_0_03_dout;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                temp_M_real_V_3_4_reg_640 <= ap_phi_reg_pp0_iter1_temp_M_real_V_3_4_reg_640;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln171_reg_1037 <= icmp_ln171_fu_806_p2;
                icmp_ln171_reg_1037_pp0_iter1_reg <= icmp_ln171_reg_1037;
                r53_reg_265_pp0_iter1_reg <= r53_reg_265;
                temp_M_imag_V_0_10_reg_1029 <= p_inData_0_1_0_0_04_dout;
                temp_M_imag_V_0_reg_1008 <= p_inData_0_1_0_0_0_dout;
                temp_M_real_V_0_10_reg_1021 <= p_inData_0_0_0_0_01_dout;
                temp_M_real_V_0_reg_1000 <= p_inData_0_0_0_0_0_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                r_reg_1016 <= r_fu_792_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln171_reg_1037 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                temp_M_imag_V_3_22_fu_86 <= ap_phi_mux_temp_M_imag_V_2_4_phi_fu_734_p8;
                temp_M_imag_V_3_23_fu_90 <= ap_phi_mux_temp_M_imag_V_1_4_phi_fu_752_p8;
                temp_M_imag_V_3_24_fu_94 <= ap_phi_mux_temp_M_imag_V_0_4_phi_fu_770_p8;
                temp_M_imag_V_3_fu_82 <= ap_phi_mux_temp_M_imag_V_3_4_phi_fu_716_p8;
                temp_M_real_V_3_22_fu_102 <= ap_phi_mux_temp_M_real_V_2_4_phi_fu_662_p8;
                temp_M_real_V_3_23_fu_106 <= ap_phi_mux_temp_M_real_V_1_4_phi_fu_680_p8;
                temp_M_real_V_3_24_fu_110 <= ap_phi_mux_temp_M_real_V_0_4_phi_fu_698_p8;
                temp_M_real_V_3_fu_98 <= ap_phi_mux_temp_M_real_V_3_4_phi_fu_644_p8;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_reset_idle_pp0 = ap_const_logic_0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, io_acc_block_signal_op28, io_acc_block_signal_op32, io_acc_block_signal_op83, io_acc_block_signal_op102, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((io_acc_block_signal_op102 = ap_const_logic_0) or (io_acc_block_signal_op83 = ap_const_logic_0))) or ((ap_start = ap_const_logic_1) and ((io_acc_block_signal_op32 = ap_const_logic_0) or (io_acc_block_signal_op28 = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, io_acc_block_signal_op28, io_acc_block_signal_op32, io_acc_block_signal_op83, io_acc_block_signal_op102, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((io_acc_block_signal_op102 = ap_const_logic_0) or (io_acc_block_signal_op83 = ap_const_logic_0))) or ((ap_start = ap_const_logic_1) and ((io_acc_block_signal_op32 = ap_const_logic_0) or (io_acc_block_signal_op28 = ap_const_logic_0))));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(io_acc_block_signal_op28, io_acc_block_signal_op32)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((io_acc_block_signal_op32 = ap_const_logic_0) or (io_acc_block_signal_op28 = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(io_acc_block_signal_op83, io_acc_block_signal_op102)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((io_acc_block_signal_op102 = ap_const_logic_0) or (io_acc_block_signal_op83 = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_157_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_157 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_block_pp0_stage0_11001, icmp_ln171_reg_1037_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln171_reg_1037_pp0_iter1_reg = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;
    ap_ext_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_int_blocking_cur_n <= (p_inData_0_1_0_0_0_blk_n and p_inData_0_1_0_0_06_blk_n and p_inData_0_1_0_0_05_blk_n and p_inData_0_1_0_0_04_blk_n and p_inData_0_0_0_0_0_blk_n and p_inData_0_0_0_0_03_blk_n and p_inData_0_0_0_0_02_blk_n and p_inData_0_0_0_0_01_blk_n);
    ap_int_blocking_n <= (ap_int_blocking_cur_n and ap_const_logic_1);

    ap_phi_mux_r53_phi_fu_269_p6_assign_proc : process(r53_reg_265, r_reg_1016, icmp_ln171_reg_1037, ap_condition_157)
    begin
        if ((ap_const_boolean_1 = ap_condition_157)) then
            if ((icmp_ln171_reg_1037 = ap_const_lv1_1)) then 
                ap_phi_mux_r53_phi_fu_269_p6 <= ap_const_lv2_0;
            elsif ((icmp_ln171_reg_1037 = ap_const_lv1_0)) then 
                ap_phi_mux_r53_phi_fu_269_p6 <= r_reg_1016;
            else 
                ap_phi_mux_r53_phi_fu_269_p6 <= r53_reg_265;
            end if;
        else 
            ap_phi_mux_r53_phi_fu_269_p6 <= r53_reg_265;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_0_1_phi_fu_374_p8_assign_proc : process(r53_reg_265, temp_M_imag_V_0_reg_1008, ap_phi_reg_pp0_iter1_temp_M_imag_V_0_1_reg_371, temp_M_imag_V_3_24_fu_94)
    begin
        if ((r53_reg_265 = ap_const_lv2_0)) then 
            ap_phi_mux_temp_M_imag_V_0_1_phi_fu_374_p8 <= temp_M_imag_V_0_reg_1008;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3))) then 
            ap_phi_mux_temp_M_imag_V_0_1_phi_fu_374_p8 <= temp_M_imag_V_3_24_fu_94;
        else 
            ap_phi_mux_temp_M_imag_V_0_1_phi_fu_374_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_0_1_reg_371;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_0_2_phi_fu_499_p8_assign_proc : process(r53_reg_265, temp_M_imag_V_0_10_reg_1029, ap_phi_mux_temp_M_imag_V_0_1_phi_fu_374_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_0_2_reg_496)
    begin
        if ((r53_reg_265 = ap_const_lv2_3)) then 
            ap_phi_mux_temp_M_imag_V_0_2_phi_fu_499_p8 <= temp_M_imag_V_0_10_reg_1029;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_0_2_phi_fu_499_p8 <= ap_phi_mux_temp_M_imag_V_0_1_phi_fu_374_p8;
        else 
            ap_phi_mux_temp_M_imag_V_0_2_phi_fu_499_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_0_2_reg_496;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_0_3_phi_fu_627_p8_assign_proc : process(p_inData_0_1_0_0_05_dout, xor_ln184_fu_860_p2, ap_phi_mux_temp_M_imag_V_0_2_phi_fu_499_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_0_3_reg_624)
    begin
        if ((xor_ln184_fu_860_p2 = ap_const_lv2_0)) then 
            ap_phi_mux_temp_M_imag_V_0_3_phi_fu_627_p8 <= p_inData_0_1_0_0_05_dout;
        elsif (((xor_ln184_fu_860_p2 = ap_const_lv2_1) or (xor_ln184_fu_860_p2 = ap_const_lv2_2) or (xor_ln184_fu_860_p2 = ap_const_lv2_3))) then 
            ap_phi_mux_temp_M_imag_V_0_3_phi_fu_627_p8 <= ap_phi_mux_temp_M_imag_V_0_2_phi_fu_499_p8;
        else 
            ap_phi_mux_temp_M_imag_V_0_3_phi_fu_627_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_0_3_reg_624;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_0_4_phi_fu_770_p8_assign_proc : process(p_inData_0_1_0_0_06_dout, r53_reg_265, ap_phi_mux_temp_M_imag_V_0_3_phi_fu_627_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_0_4_reg_766)
    begin
        if ((r53_reg_265 = ap_const_lv2_1)) then 
            ap_phi_mux_temp_M_imag_V_0_4_phi_fu_770_p8 <= p_inData_0_1_0_0_06_dout;
        elsif (((r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_0_4_phi_fu_770_p8 <= ap_phi_mux_temp_M_imag_V_0_3_phi_fu_627_p8;
        else 
            ap_phi_mux_temp_M_imag_V_0_4_phi_fu_770_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_0_4_reg_766;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_1_1_phi_fu_361_p8_assign_proc : process(r53_reg_265, temp_M_imag_V_0_reg_1008, ap_phi_reg_pp0_iter1_temp_M_imag_V_1_1_reg_358, temp_M_imag_V_3_23_fu_90)
    begin
        if ((r53_reg_265 = ap_const_lv2_1)) then 
            ap_phi_mux_temp_M_imag_V_1_1_phi_fu_361_p8 <= temp_M_imag_V_0_reg_1008;
        elsif (((r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_1_1_phi_fu_361_p8 <= temp_M_imag_V_3_23_fu_90;
        else 
            ap_phi_mux_temp_M_imag_V_1_1_phi_fu_361_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_1_1_reg_358;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_1_2_phi_fu_483_p8_assign_proc : process(r53_reg_265, temp_M_imag_V_0_10_reg_1029, ap_phi_mux_temp_M_imag_V_1_1_phi_fu_361_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_1_2_reg_480)
    begin
        if ((r53_reg_265 = ap_const_lv2_0)) then 
            ap_phi_mux_temp_M_imag_V_1_2_phi_fu_483_p8 <= temp_M_imag_V_0_10_reg_1029;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3))) then 
            ap_phi_mux_temp_M_imag_V_1_2_phi_fu_483_p8 <= ap_phi_mux_temp_M_imag_V_1_1_phi_fu_361_p8;
        else 
            ap_phi_mux_temp_M_imag_V_1_2_phi_fu_483_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_1_2_reg_480;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_1_3_phi_fu_611_p8_assign_proc : process(p_inData_0_1_0_0_05_dout, xor_ln184_fu_860_p2, ap_phi_mux_temp_M_imag_V_1_2_phi_fu_483_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_1_3_reg_608)
    begin
        if ((xor_ln184_fu_860_p2 = ap_const_lv2_1)) then 
            ap_phi_mux_temp_M_imag_V_1_3_phi_fu_611_p8 <= p_inData_0_1_0_0_05_dout;
        elsif (((xor_ln184_fu_860_p2 = ap_const_lv2_2) or (xor_ln184_fu_860_p2 = ap_const_lv2_3) or (xor_ln184_fu_860_p2 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_1_3_phi_fu_611_p8 <= ap_phi_mux_temp_M_imag_V_1_2_phi_fu_483_p8;
        else 
            ap_phi_mux_temp_M_imag_V_1_3_phi_fu_611_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_1_3_reg_608;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_1_4_phi_fu_752_p8_assign_proc : process(p_inData_0_1_0_0_06_dout, r53_reg_265, ap_phi_mux_temp_M_imag_V_1_3_phi_fu_611_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_1_4_reg_748)
    begin
        if ((r53_reg_265 = ap_const_lv2_2)) then 
            ap_phi_mux_temp_M_imag_V_1_4_phi_fu_752_p8 <= p_inData_0_1_0_0_06_dout;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_1_4_phi_fu_752_p8 <= ap_phi_mux_temp_M_imag_V_1_3_phi_fu_611_p8;
        else 
            ap_phi_mux_temp_M_imag_V_1_4_phi_fu_752_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_1_4_reg_748;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_2_1_phi_fu_348_p8_assign_proc : process(r53_reg_265, temp_M_imag_V_0_reg_1008, ap_phi_reg_pp0_iter1_temp_M_imag_V_2_1_reg_345, temp_M_imag_V_3_22_fu_86)
    begin
        if ((r53_reg_265 = ap_const_lv2_2)) then 
            ap_phi_mux_temp_M_imag_V_2_1_phi_fu_348_p8 <= temp_M_imag_V_0_reg_1008;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_2_1_phi_fu_348_p8 <= temp_M_imag_V_3_22_fu_86;
        else 
            ap_phi_mux_temp_M_imag_V_2_1_phi_fu_348_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_2_1_reg_345;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_2_2_phi_fu_467_p8_assign_proc : process(r53_reg_265, temp_M_imag_V_0_10_reg_1029, ap_phi_mux_temp_M_imag_V_2_1_phi_fu_348_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_2_2_reg_464)
    begin
        if ((r53_reg_265 = ap_const_lv2_1)) then 
            ap_phi_mux_temp_M_imag_V_2_2_phi_fu_467_p8 <= temp_M_imag_V_0_10_reg_1029;
        elsif (((r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_2_2_phi_fu_467_p8 <= ap_phi_mux_temp_M_imag_V_2_1_phi_fu_348_p8;
        else 
            ap_phi_mux_temp_M_imag_V_2_2_phi_fu_467_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_2_2_reg_464;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_2_3_phi_fu_595_p8_assign_proc : process(p_inData_0_1_0_0_05_dout, xor_ln184_fu_860_p2, ap_phi_mux_temp_M_imag_V_2_2_phi_fu_467_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_2_3_reg_592)
    begin
        if ((xor_ln184_fu_860_p2 = ap_const_lv2_2)) then 
            ap_phi_mux_temp_M_imag_V_2_3_phi_fu_595_p8 <= p_inData_0_1_0_0_05_dout;
        elsif (((xor_ln184_fu_860_p2 = ap_const_lv2_1) or (xor_ln184_fu_860_p2 = ap_const_lv2_3) or (xor_ln184_fu_860_p2 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_2_3_phi_fu_595_p8 <= ap_phi_mux_temp_M_imag_V_2_2_phi_fu_467_p8;
        else 
            ap_phi_mux_temp_M_imag_V_2_3_phi_fu_595_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_2_3_reg_592;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_2_4_phi_fu_734_p8_assign_proc : process(p_inData_0_1_0_0_06_dout, r53_reg_265, ap_phi_mux_temp_M_imag_V_2_3_phi_fu_595_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_2_4_reg_730)
    begin
        if ((r53_reg_265 = ap_const_lv2_3)) then 
            ap_phi_mux_temp_M_imag_V_2_4_phi_fu_734_p8 <= p_inData_0_1_0_0_06_dout;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_2_4_phi_fu_734_p8 <= ap_phi_mux_temp_M_imag_V_2_3_phi_fu_595_p8;
        else 
            ap_phi_mux_temp_M_imag_V_2_4_phi_fu_734_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_2_4_reg_730;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_3_1_phi_fu_335_p8_assign_proc : process(r53_reg_265, temp_M_imag_V_0_reg_1008, ap_phi_reg_pp0_iter1_temp_M_imag_V_3_1_reg_332, temp_M_imag_V_3_fu_82)
    begin
        if (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_3_1_phi_fu_335_p8 <= temp_M_imag_V_3_fu_82;
        elsif ((r53_reg_265 = ap_const_lv2_3)) then 
            ap_phi_mux_temp_M_imag_V_3_1_phi_fu_335_p8 <= temp_M_imag_V_0_reg_1008;
        else 
            ap_phi_mux_temp_M_imag_V_3_1_phi_fu_335_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_3_1_reg_332;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_3_2_phi_fu_451_p8_assign_proc : process(r53_reg_265, temp_M_imag_V_0_10_reg_1029, ap_phi_mux_temp_M_imag_V_3_1_phi_fu_335_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_3_2_reg_448)
    begin
        if (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_3_2_phi_fu_451_p8 <= ap_phi_mux_temp_M_imag_V_3_1_phi_fu_335_p8;
        elsif ((r53_reg_265 = ap_const_lv2_2)) then 
            ap_phi_mux_temp_M_imag_V_3_2_phi_fu_451_p8 <= temp_M_imag_V_0_10_reg_1029;
        else 
            ap_phi_mux_temp_M_imag_V_3_2_phi_fu_451_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_3_2_reg_448;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_3_3_phi_fu_579_p8_assign_proc : process(p_inData_0_1_0_0_05_dout, xor_ln184_fu_860_p2, ap_phi_mux_temp_M_imag_V_3_2_phi_fu_451_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_3_3_reg_576)
    begin
        if (((xor_ln184_fu_860_p2 = ap_const_lv2_1) or (xor_ln184_fu_860_p2 = ap_const_lv2_2) or (xor_ln184_fu_860_p2 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_imag_V_3_3_phi_fu_579_p8 <= ap_phi_mux_temp_M_imag_V_3_2_phi_fu_451_p8;
        elsif ((xor_ln184_fu_860_p2 = ap_const_lv2_3)) then 
            ap_phi_mux_temp_M_imag_V_3_3_phi_fu_579_p8 <= p_inData_0_1_0_0_05_dout;
        else 
            ap_phi_mux_temp_M_imag_V_3_3_phi_fu_579_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_3_3_reg_576;
        end if; 
    end process;


    ap_phi_mux_temp_M_imag_V_3_4_phi_fu_716_p8_assign_proc : process(p_inData_0_1_0_0_06_dout, r53_reg_265, ap_phi_mux_temp_M_imag_V_3_3_phi_fu_579_p8, ap_phi_reg_pp0_iter1_temp_M_imag_V_3_4_reg_712)
    begin
        if (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3))) then 
            ap_phi_mux_temp_M_imag_V_3_4_phi_fu_716_p8 <= ap_phi_mux_temp_M_imag_V_3_3_phi_fu_579_p8;
        elsif ((r53_reg_265 = ap_const_lv2_0)) then 
            ap_phi_mux_temp_M_imag_V_3_4_phi_fu_716_p8 <= p_inData_0_1_0_0_06_dout;
        else 
            ap_phi_mux_temp_M_imag_V_3_4_phi_fu_716_p8 <= ap_phi_reg_pp0_iter1_temp_M_imag_V_3_4_reg_712;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_0_1_phi_fu_322_p8_assign_proc : process(r53_reg_265, temp_M_real_V_0_reg_1000, ap_phi_reg_pp0_iter1_temp_M_real_V_0_1_reg_319, temp_M_real_V_3_24_fu_110)
    begin
        if ((r53_reg_265 = ap_const_lv2_0)) then 
            ap_phi_mux_temp_M_real_V_0_1_phi_fu_322_p8 <= temp_M_real_V_0_reg_1000;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3))) then 
            ap_phi_mux_temp_M_real_V_0_1_phi_fu_322_p8 <= temp_M_real_V_3_24_fu_110;
        else 
            ap_phi_mux_temp_M_real_V_0_1_phi_fu_322_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_0_1_reg_319;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_0_2_phi_fu_435_p8_assign_proc : process(r53_reg_265, temp_M_real_V_0_10_reg_1021, ap_phi_mux_temp_M_real_V_0_1_phi_fu_322_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_0_2_reg_432)
    begin
        if ((r53_reg_265 = ap_const_lv2_3)) then 
            ap_phi_mux_temp_M_real_V_0_2_phi_fu_435_p8 <= temp_M_real_V_0_10_reg_1021;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_0_2_phi_fu_435_p8 <= ap_phi_mux_temp_M_real_V_0_1_phi_fu_322_p8;
        else 
            ap_phi_mux_temp_M_real_V_0_2_phi_fu_435_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_0_2_reg_432;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_0_3_phi_fu_563_p8_assign_proc : process(p_inData_0_0_0_0_02_dout, xor_ln184_fu_860_p2, ap_phi_mux_temp_M_real_V_0_2_phi_fu_435_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_0_3_reg_560)
    begin
        if ((xor_ln184_fu_860_p2 = ap_const_lv2_0)) then 
            ap_phi_mux_temp_M_real_V_0_3_phi_fu_563_p8 <= p_inData_0_0_0_0_02_dout;
        elsif (((xor_ln184_fu_860_p2 = ap_const_lv2_1) or (xor_ln184_fu_860_p2 = ap_const_lv2_2) or (xor_ln184_fu_860_p2 = ap_const_lv2_3))) then 
            ap_phi_mux_temp_M_real_V_0_3_phi_fu_563_p8 <= ap_phi_mux_temp_M_real_V_0_2_phi_fu_435_p8;
        else 
            ap_phi_mux_temp_M_real_V_0_3_phi_fu_563_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_0_3_reg_560;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_0_4_phi_fu_698_p8_assign_proc : process(p_inData_0_0_0_0_03_dout, r53_reg_265, ap_phi_mux_temp_M_real_V_0_3_phi_fu_563_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_0_4_reg_694)
    begin
        if ((r53_reg_265 = ap_const_lv2_1)) then 
            ap_phi_mux_temp_M_real_V_0_4_phi_fu_698_p8 <= p_inData_0_0_0_0_03_dout;
        elsif (((r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_0_4_phi_fu_698_p8 <= ap_phi_mux_temp_M_real_V_0_3_phi_fu_563_p8;
        else 
            ap_phi_mux_temp_M_real_V_0_4_phi_fu_698_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_0_4_reg_694;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_1_1_phi_fu_309_p8_assign_proc : process(r53_reg_265, temp_M_real_V_0_reg_1000, ap_phi_reg_pp0_iter1_temp_M_real_V_1_1_reg_306, temp_M_real_V_3_23_fu_106)
    begin
        if ((r53_reg_265 = ap_const_lv2_1)) then 
            ap_phi_mux_temp_M_real_V_1_1_phi_fu_309_p8 <= temp_M_real_V_0_reg_1000;
        elsif (((r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_1_1_phi_fu_309_p8 <= temp_M_real_V_3_23_fu_106;
        else 
            ap_phi_mux_temp_M_real_V_1_1_phi_fu_309_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_1_1_reg_306;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_1_2_phi_fu_419_p8_assign_proc : process(r53_reg_265, temp_M_real_V_0_10_reg_1021, ap_phi_mux_temp_M_real_V_1_1_phi_fu_309_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_1_2_reg_416)
    begin
        if ((r53_reg_265 = ap_const_lv2_0)) then 
            ap_phi_mux_temp_M_real_V_1_2_phi_fu_419_p8 <= temp_M_real_V_0_10_reg_1021;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3))) then 
            ap_phi_mux_temp_M_real_V_1_2_phi_fu_419_p8 <= ap_phi_mux_temp_M_real_V_1_1_phi_fu_309_p8;
        else 
            ap_phi_mux_temp_M_real_V_1_2_phi_fu_419_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_1_2_reg_416;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_1_3_phi_fu_547_p8_assign_proc : process(p_inData_0_0_0_0_02_dout, xor_ln184_fu_860_p2, ap_phi_mux_temp_M_real_V_1_2_phi_fu_419_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_1_3_reg_544)
    begin
        if ((xor_ln184_fu_860_p2 = ap_const_lv2_1)) then 
            ap_phi_mux_temp_M_real_V_1_3_phi_fu_547_p8 <= p_inData_0_0_0_0_02_dout;
        elsif (((xor_ln184_fu_860_p2 = ap_const_lv2_2) or (xor_ln184_fu_860_p2 = ap_const_lv2_3) or (xor_ln184_fu_860_p2 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_1_3_phi_fu_547_p8 <= ap_phi_mux_temp_M_real_V_1_2_phi_fu_419_p8;
        else 
            ap_phi_mux_temp_M_real_V_1_3_phi_fu_547_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_1_3_reg_544;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_1_4_phi_fu_680_p8_assign_proc : process(p_inData_0_0_0_0_03_dout, r53_reg_265, ap_phi_mux_temp_M_real_V_1_3_phi_fu_547_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_1_4_reg_676)
    begin
        if ((r53_reg_265 = ap_const_lv2_2)) then 
            ap_phi_mux_temp_M_real_V_1_4_phi_fu_680_p8 <= p_inData_0_0_0_0_03_dout;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_1_4_phi_fu_680_p8 <= ap_phi_mux_temp_M_real_V_1_3_phi_fu_547_p8;
        else 
            ap_phi_mux_temp_M_real_V_1_4_phi_fu_680_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_1_4_reg_676;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_2_1_phi_fu_296_p8_assign_proc : process(r53_reg_265, temp_M_real_V_0_reg_1000, ap_phi_reg_pp0_iter1_temp_M_real_V_2_1_reg_293, temp_M_real_V_3_22_fu_102)
    begin
        if ((r53_reg_265 = ap_const_lv2_2)) then 
            ap_phi_mux_temp_M_real_V_2_1_phi_fu_296_p8 <= temp_M_real_V_0_reg_1000;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_2_1_phi_fu_296_p8 <= temp_M_real_V_3_22_fu_102;
        else 
            ap_phi_mux_temp_M_real_V_2_1_phi_fu_296_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_2_1_reg_293;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_2_2_phi_fu_403_p8_assign_proc : process(r53_reg_265, temp_M_real_V_0_10_reg_1021, ap_phi_mux_temp_M_real_V_2_1_phi_fu_296_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_2_2_reg_400)
    begin
        if ((r53_reg_265 = ap_const_lv2_1)) then 
            ap_phi_mux_temp_M_real_V_2_2_phi_fu_403_p8 <= temp_M_real_V_0_10_reg_1021;
        elsif (((r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_2_2_phi_fu_403_p8 <= ap_phi_mux_temp_M_real_V_2_1_phi_fu_296_p8;
        else 
            ap_phi_mux_temp_M_real_V_2_2_phi_fu_403_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_2_2_reg_400;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_2_3_phi_fu_531_p8_assign_proc : process(p_inData_0_0_0_0_02_dout, xor_ln184_fu_860_p2, ap_phi_mux_temp_M_real_V_2_2_phi_fu_403_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_2_3_reg_528)
    begin
        if ((xor_ln184_fu_860_p2 = ap_const_lv2_2)) then 
            ap_phi_mux_temp_M_real_V_2_3_phi_fu_531_p8 <= p_inData_0_0_0_0_02_dout;
        elsif (((xor_ln184_fu_860_p2 = ap_const_lv2_1) or (xor_ln184_fu_860_p2 = ap_const_lv2_3) or (xor_ln184_fu_860_p2 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_2_3_phi_fu_531_p8 <= ap_phi_mux_temp_M_real_V_2_2_phi_fu_403_p8;
        else 
            ap_phi_mux_temp_M_real_V_2_3_phi_fu_531_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_2_3_reg_528;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_2_4_phi_fu_662_p8_assign_proc : process(p_inData_0_0_0_0_03_dout, r53_reg_265, ap_phi_mux_temp_M_real_V_2_3_phi_fu_531_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_2_4_reg_658)
    begin
        if ((r53_reg_265 = ap_const_lv2_3)) then 
            ap_phi_mux_temp_M_real_V_2_4_phi_fu_662_p8 <= p_inData_0_0_0_0_03_dout;
        elsif (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_2_4_phi_fu_662_p8 <= ap_phi_mux_temp_M_real_V_2_3_phi_fu_531_p8;
        else 
            ap_phi_mux_temp_M_real_V_2_4_phi_fu_662_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_2_4_reg_658;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_3_1_phi_fu_283_p8_assign_proc : process(r53_reg_265, temp_M_real_V_0_reg_1000, ap_phi_reg_pp0_iter1_temp_M_real_V_3_1_reg_280, temp_M_real_V_3_fu_98)
    begin
        if (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_3_1_phi_fu_283_p8 <= temp_M_real_V_3_fu_98;
        elsif ((r53_reg_265 = ap_const_lv2_3)) then 
            ap_phi_mux_temp_M_real_V_3_1_phi_fu_283_p8 <= temp_M_real_V_0_reg_1000;
        else 
            ap_phi_mux_temp_M_real_V_3_1_phi_fu_283_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_3_1_reg_280;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_3_2_phi_fu_387_p8_assign_proc : process(r53_reg_265, temp_M_real_V_0_10_reg_1021, ap_phi_mux_temp_M_real_V_3_1_phi_fu_283_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_3_2_reg_384)
    begin
        if (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_3) or (r53_reg_265 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_3_2_phi_fu_387_p8 <= ap_phi_mux_temp_M_real_V_3_1_phi_fu_283_p8;
        elsif ((r53_reg_265 = ap_const_lv2_2)) then 
            ap_phi_mux_temp_M_real_V_3_2_phi_fu_387_p8 <= temp_M_real_V_0_10_reg_1021;
        else 
            ap_phi_mux_temp_M_real_V_3_2_phi_fu_387_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_3_2_reg_384;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_3_3_phi_fu_515_p8_assign_proc : process(p_inData_0_0_0_0_02_dout, xor_ln184_fu_860_p2, ap_phi_mux_temp_M_real_V_3_2_phi_fu_387_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_3_3_reg_512)
    begin
        if (((xor_ln184_fu_860_p2 = ap_const_lv2_1) or (xor_ln184_fu_860_p2 = ap_const_lv2_2) or (xor_ln184_fu_860_p2 = ap_const_lv2_0))) then 
            ap_phi_mux_temp_M_real_V_3_3_phi_fu_515_p8 <= ap_phi_mux_temp_M_real_V_3_2_phi_fu_387_p8;
        elsif ((xor_ln184_fu_860_p2 = ap_const_lv2_3)) then 
            ap_phi_mux_temp_M_real_V_3_3_phi_fu_515_p8 <= p_inData_0_0_0_0_02_dout;
        else 
            ap_phi_mux_temp_M_real_V_3_3_phi_fu_515_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_3_3_reg_512;
        end if; 
    end process;


    ap_phi_mux_temp_M_real_V_3_4_phi_fu_644_p8_assign_proc : process(p_inData_0_0_0_0_03_dout, r53_reg_265, ap_phi_mux_temp_M_real_V_3_3_phi_fu_515_p8, ap_phi_reg_pp0_iter1_temp_M_real_V_3_4_reg_640)
    begin
        if (((r53_reg_265 = ap_const_lv2_1) or (r53_reg_265 = ap_const_lv2_2) or (r53_reg_265 = ap_const_lv2_3))) then 
            ap_phi_mux_temp_M_real_V_3_4_phi_fu_644_p8 <= ap_phi_mux_temp_M_real_V_3_3_phi_fu_515_p8;
        elsif ((r53_reg_265 = ap_const_lv2_0)) then 
            ap_phi_mux_temp_M_real_V_3_4_phi_fu_644_p8 <= p_inData_0_0_0_0_03_dout;
        else 
            ap_phi_mux_temp_M_real_V_3_4_phi_fu_644_p8 <= ap_phi_reg_pp0_iter1_temp_M_real_V_3_4_reg_640;
        end if; 
    end process;

    ap_phi_reg_pp0_iter1_temp_M_imag_V_0_1_reg_371 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_0_2_reg_496 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_0_3_reg_624 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_0_4_reg_766 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_1_1_reg_358 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_1_2_reg_480 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_1_3_reg_608 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_1_4_reg_748 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_2_1_reg_345 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_2_2_reg_464 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_2_3_reg_592 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_2_4_reg_730 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_3_1_reg_332 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_3_2_reg_448 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_3_3_reg_576 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_imag_V_3_4_reg_712 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_0_1_reg_319 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_0_2_reg_432 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_0_3_reg_560 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_0_4_reg_694 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_1_1_reg_306 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_1_2_reg_416 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_1_3_reg_544 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_1_4_reg_676 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_2_1_reg_293 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_2_2_reg_400 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_2_3_reg_528 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_2_4_reg_658 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_3_1_reg_280 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_3_2_reg_384 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_3_3_reg_512 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_temp_M_real_V_3_4_reg_640 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(ap_start, icmp_ln171_fu_806_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (icmp_ln171_fu_806_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_str_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);
    icmp_ln171_fu_806_p2 <= "1" when (ap_phi_mux_r53_phi_fu_269_p6 = ap_const_lv2_3) else "0";
    io_acc_block_signal_op102 <= (p_inData_0_1_0_0_06_empty_n and p_inData_0_0_0_0_03_empty_n);
    io_acc_block_signal_op28 <= (p_inData_0_1_0_0_0_empty_n and p_inData_0_0_0_0_0_empty_n);
    io_acc_block_signal_op32 <= (p_inData_0_1_0_0_04_empty_n and p_inData_0_0_0_0_01_empty_n);
    io_acc_block_signal_op83 <= (p_inData_0_1_0_0_05_empty_n and p_inData_0_0_0_0_02_empty_n);
    p_digitReseversedOutputBuff_M_imag10_address0 <= zext_ln171_fu_938_p1(2 - 1 downto 0);

    p_digitReseversedOutputBuff_M_imag10_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_imag10_ce0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_imag10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_imag10_d0 <= temp_M_imag_V_1_4_reg_748;

    p_digitReseversedOutputBuff_M_imag10_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_imag10_we0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_imag10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_imag11_address0 <= zext_ln171_fu_938_p1(2 - 1 downto 0);

    p_digitReseversedOutputBuff_M_imag11_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_imag11_ce0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_imag11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_imag11_d0 <= temp_M_imag_V_2_4_reg_730;

    p_digitReseversedOutputBuff_M_imag11_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_imag11_we0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_imag11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_imag12_address0 <= zext_ln171_fu_938_p1(2 - 1 downto 0);

    p_digitReseversedOutputBuff_M_imag12_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_imag12_ce0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_imag12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_imag12_d0 <= temp_M_imag_V_3_4_reg_712;

    p_digitReseversedOutputBuff_M_imag12_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_imag12_we0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_imag12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_imag_address0 <= zext_ln171_fu_938_p1(2 - 1 downto 0);

    p_digitReseversedOutputBuff_M_imag_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_imag_ce0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_imag_d0 <= temp_M_imag_V_0_4_reg_766;

    p_digitReseversedOutputBuff_M_imag_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_imag_we0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_real7_address0 <= zext_ln171_fu_938_p1(2 - 1 downto 0);

    p_digitReseversedOutputBuff_M_real7_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_real7_ce0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_real7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_real7_d0 <= temp_M_real_V_1_4_reg_676;

    p_digitReseversedOutputBuff_M_real7_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_real7_we0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_real7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_real8_address0 <= zext_ln171_fu_938_p1(2 - 1 downto 0);

    p_digitReseversedOutputBuff_M_real8_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_real8_ce0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_real8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_real8_d0 <= temp_M_real_V_2_4_reg_658;

    p_digitReseversedOutputBuff_M_real8_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_real8_we0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_real8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_real9_address0 <= zext_ln171_fu_938_p1(2 - 1 downto 0);

    p_digitReseversedOutputBuff_M_real9_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_real9_ce0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_real9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_real9_d0 <= temp_M_real_V_3_4_reg_640;

    p_digitReseversedOutputBuff_M_real9_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_real9_we0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_real9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_real_address0 <= zext_ln171_fu_938_p1(2 - 1 downto 0);

    p_digitReseversedOutputBuff_M_real_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_real_ce0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_digitReseversedOutputBuff_M_real_d0 <= temp_M_real_V_0_4_reg_694;

    p_digitReseversedOutputBuff_M_real_we0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_digitReseversedOutputBuff_M_real_we0 <= ap_const_logic_1;
        else 
            p_digitReseversedOutputBuff_M_real_we0 <= ap_const_logic_0;
        end if; 
    end process;


    p_inData_0_0_0_0_01_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, p_inData_0_0_0_0_01_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_0_0_0_01_blk_n <= p_inData_0_0_0_0_01_empty_n;
        else 
            p_inData_0_0_0_0_01_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_inData_0_0_0_0_01_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_0_0_0_01_read <= ap_const_logic_1;
        else 
            p_inData_0_0_0_0_01_read <= ap_const_logic_0;
        end if; 
    end process;


    p_inData_0_0_0_0_02_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, p_inData_0_0_0_0_02_empty_n, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_0_0_0_02_blk_n <= p_inData_0_0_0_0_02_empty_n;
        else 
            p_inData_0_0_0_0_02_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_inData_0_0_0_0_02_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_0_0_0_02_read <= ap_const_logic_1;
        else 
            p_inData_0_0_0_0_02_read <= ap_const_logic_0;
        end if; 
    end process;


    p_inData_0_0_0_0_03_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, p_inData_0_0_0_0_03_empty_n, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_0_0_0_03_blk_n <= p_inData_0_0_0_0_03_empty_n;
        else 
            p_inData_0_0_0_0_03_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_inData_0_0_0_0_03_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_0_0_0_03_read <= ap_const_logic_1;
        else 
            p_inData_0_0_0_0_03_read <= ap_const_logic_0;
        end if; 
    end process;


    p_inData_0_0_0_0_0_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, p_inData_0_0_0_0_0_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_0_0_0_0_blk_n <= p_inData_0_0_0_0_0_empty_n;
        else 
            p_inData_0_0_0_0_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_inData_0_0_0_0_0_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_0_0_0_0_read <= ap_const_logic_1;
        else 
            p_inData_0_0_0_0_0_read <= ap_const_logic_0;
        end if; 
    end process;


    p_inData_0_1_0_0_04_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, p_inData_0_1_0_0_04_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_1_0_0_04_blk_n <= p_inData_0_1_0_0_04_empty_n;
        else 
            p_inData_0_1_0_0_04_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_inData_0_1_0_0_04_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_1_0_0_04_read <= ap_const_logic_1;
        else 
            p_inData_0_1_0_0_04_read <= ap_const_logic_0;
        end if; 
    end process;


    p_inData_0_1_0_0_05_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, p_inData_0_1_0_0_05_empty_n, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_1_0_0_05_blk_n <= p_inData_0_1_0_0_05_empty_n;
        else 
            p_inData_0_1_0_0_05_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_inData_0_1_0_0_05_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_1_0_0_05_read <= ap_const_logic_1;
        else 
            p_inData_0_1_0_0_05_read <= ap_const_logic_0;
        end if; 
    end process;


    p_inData_0_1_0_0_06_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, p_inData_0_1_0_0_06_empty_n, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_1_0_0_06_blk_n <= p_inData_0_1_0_0_06_empty_n;
        else 
            p_inData_0_1_0_0_06_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_inData_0_1_0_0_06_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_1_0_0_06_read <= ap_const_logic_1;
        else 
            p_inData_0_1_0_0_06_read <= ap_const_logic_0;
        end if; 
    end process;


    p_inData_0_1_0_0_0_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, p_inData_0_1_0_0_0_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_1_0_0_0_blk_n <= p_inData_0_1_0_0_0_empty_n;
        else 
            p_inData_0_1_0_0_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_inData_0_1_0_0_0_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_inData_0_1_0_0_0_read <= ap_const_logic_1;
        else 
            p_inData_0_1_0_0_0_read <= ap_const_logic_0;
        end if; 
    end process;

    r_fu_792_p2 <= std_logic_vector(unsigned(ap_phi_mux_r53_phi_fu_269_p6) + unsigned(ap_const_lv2_1));
    xor_ln184_fu_860_p2 <= (r53_reg_265 xor ap_const_lv2_2);
    zext_ln171_fu_938_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r53_reg_265_pp0_iter1_reg),64));
end behav;
