log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/ap_idle
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/ap_idle -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/ap_int_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/ap_ext_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/ap_str_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/ap_str_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/ap_idle
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/ap_idle -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/ap_int_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/ap_ext_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/ap_str_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/ap_str_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/readImages_512u_16u_16u_4096u_22u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_22_8_5_3_0_U0/ap_idle
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/readImages_512u_16u_16u_4096u_22u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_22_8_5_3_0_U0/ap_idle -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/readImages_512u_16u_16u_4096u_22u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_22_8_5_3_0_U0/ap_int_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/readImages_512u_16u_16u_4096u_22u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_22_8_5_3_0_U0/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/readImages_512u_16u_16u_4096u_22u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_22_8_5_3_0_U0/ap_ext_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/readImages_512u_16u_16u_4096u_22u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_22_8_5_3_0_U0/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/readImages_512u_16u_16u_4096u_22u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_22_8_5_3_0_U0/ap_str_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/readImages_512u_16u_16u_4096u_22u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_22_8_5_3_0_U0/ap_str_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_Loop_VITIS_LOOP_126_1_proc_U0/ap_idle
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_Loop_VITIS_LOOP_126_1_proc_U0/ap_idle -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_Loop_VITIS_LOOP_126_1_proc_U0/ap_int_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_Loop_VITIS_LOOP_126_1_proc_U0/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_Loop_VITIS_LOOP_126_1_proc_U0/ap_ext_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_Loop_VITIS_LOOP_126_1_proc_U0/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_Loop_VITIS_LOOP_126_1_proc_U0/ap_str_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_Loop_VITIS_LOOP_126_1_proc_U0/ap_str_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/entry_proc_U0/ap_idle
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/entry_proc_U0/ap_idle -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/entry_proc_U0/ap_int_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/entry_proc_U0/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/entry_proc_U0/ap_ext_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/entry_proc_U0/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/entry_proc_U0/ap_str_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/entry_proc_U0/ap_str_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/writeImages_512u_16u_16u_4096u_32u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_32_18_5_3_0_U0/ap_idle
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/writeImages_512u_16u_16u_4096u_32u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_32_18_5_3_0_U0/ap_idle -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/writeImages_512u_16u_16u_4096u_32u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_32_18_5_3_0_U0/ap_int_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/writeImages_512u_16u_16u_4096u_32u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_32_18_5_3_0_U0/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/writeImages_512u_16u_16u_4096u_32u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_32_18_5_3_0_U0/ap_ext_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/writeImages_512u_16u_16u_4096u_32u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_32_18_5_3_0_U0/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/writeImages_512u_16u_16u_4096u_32u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_32_18_5_3_0_U0/ap_str_blocking_n
get_value_database /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst/grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/writeImages_512u_16u_16u_4096u_32u_8u_complex_ap_fixed_22_8_5_3_0_SuperSampleContainer_8_complex_ap_fixed_32_18_5_3_0_U0/ap_str_blocking_n -time 0 -quiet 

log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local2_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local2_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local2_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local2_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local2_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local2_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local2_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_5_U0/fftOutData_local2_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_4_U0/fftOutData_local_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_4_U0/fftOutData_local2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//innerFFT_16_4_40002_0_0_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_27_13_5_3_0_U0/casted_output_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//innerFFT_16_4_40002_0_0_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_27_13_5_3_0_U0/p_fftInData_reOrdered_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftInStrm_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftInStrm_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftInStrm_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftInStrm_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftInStrm_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftInStrm_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftInStrm_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftInStrm_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftOutStrm_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftOutStrm_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftOutStrm_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftOutStrm_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftOutStrm_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftOutStrm_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftOutStrm_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_2_fu_96/fftOutStrm_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local2_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local2_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local2_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local2_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local2_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local2_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local2_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_7_U0/fftOutData_local2_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_6_U0/fftOutData_local_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_6_U0/fftOutData_local2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//innerFFT_16_4_40001_0_0_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_27_13_5_3_0_U0/casted_output_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//innerFFT_16_4_40001_0_0_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_27_13_5_3_0_U0/p_fftInData_reOrdered_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftInStrm_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftInStrm_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftInStrm_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftInStrm_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftInStrm_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftInStrm_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftInStrm_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftInStrm_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftOutStrm_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftOutStrm_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftOutStrm_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftOutStrm_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftOutStrm_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftOutStrm_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftOutStrm_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_3_fu_96/fftOutStrm_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//genMemWideFFTKernel1DArray_3_U0/ssrWideStream4kernelIn_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//genMemWideFFTKernel1DArray_3_U0/ssrWideStream4kernelOut_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//genMemWideFFTKernel1DArray_1_U0/ssrWideStream4kernelIn_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//genMemWideFFTKernel1DArray_1_U0/ssrWideStream4kernelOut_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_1_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local2_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local2_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local2_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local2_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local2_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local2_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local2_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_1_U0/fftOutData_local2_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_U0/fftOutData_local_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_U0/fftOutData_local2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//innerFFT_16_4_80002_0_0_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_27_13_5_3_0_complex_ap_fixed_32_18_5_3_0_U0/casted_output_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//innerFFT_16_4_80002_0_0_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_27_13_5_3_0_complex_ap_fixed_32_18_5_3_0_U0/p_fftInData_reOrdered_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftInStrm_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftInStrm_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftInStrm_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftInStrm_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftInStrm_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftInStrm_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftInStrm_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftInStrm_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftOutStrm_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftOutStrm_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftOutStrm_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftOutStrm_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftOutStrm_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftOutStrm_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftOutStrm_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_fu_96/fftOutStrm_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local2_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local2_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local2_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local2_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local2_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local2_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local2_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_3_U0/fftOutData_local2_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_2_U0/fftOutData_local_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//fftStage_2_U0/fftOutData_local2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//innerFFT_16_4_80001_0_0_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_27_13_5_3_0_complex_ap_fixed_32_18_5_3_0_U0/casted_output_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//innerFFT_16_4_80001_0_0_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_27_13_5_3_0_complex_ap_fixed_32_18_5_3_0_U0/p_fftInData_reOrdered_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftInStrm_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftInStrm_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftInStrm_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftInStrm_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftInStrm_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftInStrm_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftInStrm_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftInStrm_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftOutStrm_V_M_real_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftOutStrm_V_M_real_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftOutStrm_V_M_real_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftOutStrm_V_M_real_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftOutStrm_V_M_imag_V_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftOutStrm_V_M_imag_V_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftOutStrm_V_M_imag_V_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fftStreamingKernelBody_1_fu_96/fftOutStrm_V_M_imag_V_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//genMemWideFFTKernel1DArray_2_U0/ssrWideStream4kernelIn_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//genMemWideFFTKernel1DArray_2_U0/ssrWideStream4kernelOut_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//genMemWideFFTKernel1DArray_U0/ssrWideStream4kernelIn_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//genMemWideFFTKernel1DArray_U0/ssrWideStream4kernelOut_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_0_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_real_V_1_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_0_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/demuxStreamArrayOut_V_superSample_M_imag_V_1_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_0_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_real_V_1_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_0_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_0_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_1_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_3_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_4_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_5_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_6_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//sliceProcessor_U0/sliceProcesorStreamArrayOut_V_superSample_M_imag_V_1_7_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dProc_fu_276/l_transBlkMatrixStream_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dProc_fu_276/l_rowProcOutStream_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dProc_fu_276/l_invTranspBlkMatrixStream_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dProc_fu_276/l_transpMatrixStream_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dProc_fu_276/l_transpBlkMatrixStream2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dProc_fu_276/l_colProcOutStream_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dProc_fu_276/l_invTranspBlkMatrixStream2_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fftInStrm_U/mOutPtr
log_wave -quiet /emu_wrapper/emu_i/dynamic_region/fft2DKernel_1/inst//grp_fft2dKernel_512u_8u_16u_16u_4096u_22u_32u_2u_FFTParams_FFTParams2_40000u_80000u_complex_ap_fixed_22_8_5_3_0_complex_ap_fixed_32_18_5_3_0_s_fu_286/fftOutStrm_U/mOutPtr
