// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft2DKernel_fftStageKernelS2S_16_4_0_0_0_2_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_27_13_5_3_0_complex_ap_fixed_30_16_5_3_0_87 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_fftInData_reOrdered_dout,
        p_fftInData_reOrdered_empty_n,
        p_fftInData_reOrdered_read,
        fftOutData_local_din,
        fftOutData_local_full_n,
        fftOutData_local_write,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] p_fftInData_reOrdered_dout;
input   p_fftInData_reOrdered_empty_n;
output   p_fftInData_reOrdered_read;
output  [255:0] fftOutData_local_din;
input   fftOutData_local_full_n;
output   fftOutData_local_write;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_fftInData_reOrdered_read;
reg fftOutData_local_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln151_fu_274_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_nbreadreq_fu_98_p3;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
reg   [0:0] tmp_reg_747;
reg   [0:0] tmp_reg_747_pp0_iter5_reg;
reg    ap_block_state8_pp0_stage0_iter6;
reg    ap_enable_reg_pp0_iter6;
reg    ap_block_pp0_stage0_11001;
wire   [17:0] twiddleObj_twiddleTable_M_imag_V_q0;
wire   [17:0] twiddleObj_twiddleTable_M_imag_V_q1;
wire   [17:0] twiddleObj_twiddleTable_M_imag_V_q2;
wire   [17:0] twiddleObj_twiddleTable_M_imag_V_q3;
wire   [17:0] twiddleObj_twiddleTable_M_imag_V_q4;
wire   [17:0] twiddleObj_twiddleTable_M_imag_V_q5;
wire   [17:0] twiddleObj_twiddleTable_M_imag_V_q6;
reg    p_fftInData_reOrdered_blk_n;
wire    ap_block_pp0_stage0;
reg    fftOutData_local_blk_n;
reg   [31:0] k1_reg_134;
reg   [0:0] tmp_reg_747_pp0_iter1_reg;
reg   [0:0] tmp_reg_747_pp0_iter2_reg;
reg   [0:0] tmp_reg_747_pp0_iter3_reg;
reg   [0:0] tmp_reg_747_pp0_iter4_reg;
wire   [26:0] X_of_ns_M_real_V_0_fu_180_p1;
reg   [26:0] X_of_ns_M_real_V_0_reg_751;
reg   [26:0] X_of_ns_M_imag_V_0_reg_756;
reg  signed [26:0] X_of_ns_M_real_V_1_reg_761;
reg  signed [26:0] X_of_ns_M_imag_V_1_reg_767;
reg  signed [26:0] X_of_ns_M_real_V_2_reg_773;
reg  signed [26:0] X_of_ns_M_imag_V_2_reg_779;
reg  signed [26:0] X_of_ns_M_real_V_3_reg_785;
reg  signed [26:0] X_of_ns_M_imag_V_3_reg_791;
wire   [3:0] trunc_ln151_fu_254_p1;
reg   [3:0] trunc_ln151_reg_797;
reg   [3:0] trunc_ln151_reg_797_pp0_iter1_reg;
wire   [31:0] k_fu_258_p2;
reg   [31:0] k_reg_802;
reg   [0:0] icmp_ln151_reg_807;
reg   [0:0] icmp_ln151_reg_807_pp0_iter1_reg;
reg   [0:0] icmp_ln151_reg_807_pp0_iter2_reg;
reg   [0:0] icmp_ln151_reg_807_pp0_iter3_reg;
reg   [0:0] icmp_ln151_reg_807_pp0_iter4_reg;
reg   [0:0] icmp_ln151_reg_807_pp0_iter5_reg;
wire   [28:0] bflyOutData_M_real_V_0_fu_347_p2;
reg   [28:0] bflyOutData_M_real_V_0_reg_811;
wire   [28:0] bflyOutData_M_imag_V_0_fu_361_p2;
reg   [28:0] bflyOutData_M_imag_V_0_reg_816;
wire   [28:0] bflyOutData_M_real_V_1_fu_513_p2;
reg   [28:0] bflyOutData_M_real_V_1_reg_821;
wire   [28:0] bflyOutData_M_imag_V_1_fu_527_p2;
reg   [28:0] bflyOutData_M_imag_V_1_reg_826;
wire   [28:0] bflyOutData_M_real_V_2_fu_602_p2;
reg   [28:0] bflyOutData_M_real_V_2_reg_831;
wire   [28:0] bflyOutData_M_imag_V_2_fu_616_p2;
reg   [28:0] bflyOutData_M_imag_V_2_reg_836;
wire   [28:0] bflyOutData_M_real_V_3_fu_654_p2;
reg   [28:0] bflyOutData_M_real_V_3_reg_841;
wire   [28:0] bflyOutData_M_imag_V_3_fu_668_p2;
reg   [28:0] bflyOutData_M_imag_V_3_reg_846;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_done;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_idle;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ready;
reg    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ce;
wire   [3:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address0;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce0;
wire   [3:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address1;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce1;
wire   [3:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address2;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce2;
wire   [3:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address3;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce3;
wire   [3:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address4;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce4;
wire   [3:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address5;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce5;
wire   [3:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address6;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce6;
wire   [29:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_0;
wire   [29:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_1;
wire   [29:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_2;
wire   [29:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_3;
wire   [29:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_4;
wire   [29:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_5;
wire   [29:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_6;
wire   [29:0] grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_7;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ext_blocking_n;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_str_blocking_n;
wire    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_int_blocking_n;
reg    ap_block_state2_pp0_stage0_iter0_ignore_call82;
wire    ap_block_state3_pp0_stage0_iter1_ignore_call82;
wire    ap_block_state4_pp0_stage0_iter2_ignore_call82;
wire    ap_block_state5_pp0_stage0_iter3_ignore_call82;
wire    ap_block_state6_pp0_stage0_iter4_ignore_call82;
wire    ap_block_state7_pp0_stage0_iter5_ignore_call82;
reg    ap_block_state8_pp0_stage0_iter6_ignore_call82;
reg    ap_block_pp0_stage0_11001_ignoreCallOp113;
reg   [31:0] ap_phi_mux_k1_phi_fu_138_p6;
reg   [31:0] ap_phi_mux_k_1_phi_fu_151_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_k_1_reg_148;
wire   [31:0] k_2_fu_173_p2;
reg    grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start_reg;
reg    ap_block_pp0_stage0_01001;
wire   [29:0] tmp_96_fu_264_p4;
wire   [42:0] r_V_34_fu_289_p3;
wire  signed [27:0] sext_ln717_2_fu_286_p1;
wire  signed [27:0] sext_ln717_fu_280_p1;
wire  signed [27:0] sext_ln717_3_fu_300_p1;
wire  signed [27:0] sext_ln717_1_fu_283_p1;
wire  signed [27:0] sext_ln1245_fu_315_p1;
wire  signed [27:0] sext_ln1245_1_fu_318_p1;
wire  signed [27:0] sext_ln1245_2_fu_327_p1;
wire  signed [27:0] sext_ln1245_3_fu_330_p1;
wire   [27:0] add_ln712_2_fu_321_p2;
wire   [27:0] add_ln712_fu_303_p2;
wire  signed [28:0] sext_ln712_fu_339_p1;
wire  signed [28:0] sext_ln712_15_fu_343_p1;
wire   [27:0] add_ln712_3_fu_333_p2;
wire   [27:0] add_ln712_1_fu_309_p2;
wire  signed [28:0] sext_ln712_16_fu_353_p1;
wire  signed [28:0] sext_ln712_17_fu_357_p1;
wire  signed [43:0] sext_ln1168_fu_296_p1;
wire   [42:0] shl_ln_fu_373_p3;
wire  signed [43:0] sext_ln1171_fu_380_p1;
wire   [43:0] r_V_fu_384_p2;
wire   [42:0] shl_ln1171_1_fu_400_p3;
wire  signed [43:0] sext_ln1171_29_fu_407_p1;
wire   [43:0] r_V_29_fu_411_p2;
wire   [42:0] shl_ln1171_2_fu_427_p3;
wire  signed [43:0] sext_ln1171_30_fu_434_p1;
wire   [43:0] r_V_30_fu_438_p2;
wire   [42:0] r_V_36_fu_454_p3;
wire  signed [43:0] sext_ln1168_1_fu_461_p1;
wire   [43:0] ret_V_fu_465_p2;
wire   [27:0] p_val_V_18_fu_390_p4;
wire   [27:0] p_val_V_21_fu_471_p4;
wire   [27:0] p_val_V_19_fu_417_p4;
wire   [27:0] p_val_V_20_fu_444_p4;
wire   [27:0] add_ln712_8_fu_493_p2;
wire   [27:0] add_ln712_6_fu_481_p2;
wire  signed [28:0] sext_ln712_18_fu_505_p1;
wire  signed [28:0] sext_ln712_19_fu_509_p1;
wire   [27:0] add_ln712_9_fu_499_p2;
wire   [27:0] add_ln712_7_fu_487_p2;
wire  signed [28:0] sext_ln712_20_fu_519_p1;
wire  signed [28:0] sext_ln712_21_fu_523_p1;
wire   [43:0] r_V_35_fu_367_p2;
wire   [42:0] shl_ln1171_4_fu_543_p3;
wire  signed [43:0] sext_ln1171_31_fu_550_p1;
wire   [43:0] r_V_32_fu_554_p2;
wire   [27:0] p_val_V_22_fu_533_p4;
wire   [27:0] p_val_V_23_fu_560_p4;
wire   [27:0] add_ln712_14_fu_582_p2;
wire   [27:0] add_ln712_12_fu_570_p2;
wire  signed [28:0] sext_ln712_22_fu_594_p1;
wire  signed [28:0] sext_ln712_23_fu_598_p1;
wire   [27:0] add_ln712_15_fu_588_p2;
wire   [27:0] add_ln712_13_fu_576_p2;
wire  signed [28:0] sext_ln712_24_fu_608_p1;
wire  signed [28:0] sext_ln712_25_fu_612_p1;
wire   [27:0] add_ln712_20_fu_634_p2;
wire   [27:0] add_ln712_18_fu_622_p2;
wire  signed [28:0] sext_ln712_26_fu_646_p1;
wire  signed [28:0] sext_ln712_27_fu_650_p1;
wire   [27:0] add_ln712_21_fu_640_p2;
wire   [27:0] add_ln712_19_fu_628_p2;
wire  signed [28:0] sext_ln712_28_fu_660_p1;
wire  signed [28:0] sext_ln712_29_fu_664_p1;
wire   [253:0] tmp_s_fu_706_p16;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to5;
reg    ap_reset_idle_pp0;
wire    ap_int_blocking_cur_n;
reg    ap_ext_blocking_sub_n;
reg    ap_wait_0;
reg    ap_sub_ext_blocking_0;
reg    ap_str_blocking_sub_n;
reg    ap_sub_str_blocking_0;
reg    ap_int_blocking_sub_n;
reg    ap_sub_int_blocking_0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_271;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start_reg = 1'b0;
end

fft2DKernel_fftStageKernelS2S_16_4_0_0_0_2_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_bll #(
    .DataWidth( 18 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
twiddleObj_twiddleTable_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address0),
    .ce0(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce0),
    .q0(twiddleObj_twiddleTable_M_imag_V_q0),
    .address1(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address1),
    .ce1(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce1),
    .q1(twiddleObj_twiddleTable_M_imag_V_q1),
    .address2(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address2),
    .ce2(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce2),
    .q2(twiddleObj_twiddleTable_M_imag_V_q2),
    .address3(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address3),
    .ce3(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce3),
    .q3(twiddleObj_twiddleTable_M_imag_V_q3),
    .address4(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address4),
    .ce4(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce4),
    .q4(twiddleObj_twiddleTable_M_imag_V_q4),
    .address5(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address5),
    .ce5(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce5),
    .q5(twiddleObj_twiddleTable_M_imag_V_q5),
    .address6(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address6),
    .ce6(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce6),
    .q6(twiddleObj_twiddleTable_M_imag_V_q6)
);

fft2DKernel_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start),
    .ap_done(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_done),
    .ap_idle(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_idle),
    .ap_ready(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ready),
    .ap_ce(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ce),
    .p_read(bflyOutData_M_real_V_0_reg_811),
    .p_read1(bflyOutData_M_real_V_1_reg_821),
    .p_read2(bflyOutData_M_real_V_2_reg_831),
    .p_read3(bflyOutData_M_real_V_3_reg_841),
    .p_read4(bflyOutData_M_imag_V_0_reg_816),
    .p_read5(bflyOutData_M_imag_V_1_reg_826),
    .p_read6(bflyOutData_M_imag_V_2_reg_836),
    .p_read7(bflyOutData_M_imag_V_3_reg_846),
    .p_twiddleTable_M_imag_0_0_0_address0(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address0),
    .p_twiddleTable_M_imag_0_0_0_ce0(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce0),
    .p_twiddleTable_M_imag_0_0_0_q0(twiddleObj_twiddleTable_M_imag_V_q0),
    .p_twiddleTable_M_imag_0_0_0_address1(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address1),
    .p_twiddleTable_M_imag_0_0_0_ce1(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce1),
    .p_twiddleTable_M_imag_0_0_0_q1(twiddleObj_twiddleTable_M_imag_V_q1),
    .p_twiddleTable_M_imag_0_0_0_address2(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address2),
    .p_twiddleTable_M_imag_0_0_0_ce2(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce2),
    .p_twiddleTable_M_imag_0_0_0_q2(twiddleObj_twiddleTable_M_imag_V_q2),
    .p_twiddleTable_M_imag_0_0_0_address3(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address3),
    .p_twiddleTable_M_imag_0_0_0_ce3(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce3),
    .p_twiddleTable_M_imag_0_0_0_q3(twiddleObj_twiddleTable_M_imag_V_q3),
    .p_twiddleTable_M_imag_0_0_0_address4(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address4),
    .p_twiddleTable_M_imag_0_0_0_ce4(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce4),
    .p_twiddleTable_M_imag_0_0_0_q4(twiddleObj_twiddleTable_M_imag_V_q4),
    .p_twiddleTable_M_imag_0_0_0_address5(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address5),
    .p_twiddleTable_M_imag_0_0_0_ce5(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce5),
    .p_twiddleTable_M_imag_0_0_0_q5(twiddleObj_twiddleTable_M_imag_V_q5),
    .p_twiddleTable_M_imag_0_0_0_address6(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_address6),
    .p_twiddleTable_M_imag_0_0_0_ce6(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_p_twiddleTable_M_imag_0_0_0_ce6),
    .p_twiddleTable_M_imag_0_0_0_q6(twiddleObj_twiddleTable_M_imag_V_q6),
    .p_k(trunc_ln151_reg_797_pp0_iter1_reg),
    .ap_return_0(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_0),
    .ap_return_1(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_1),
    .ap_return_2(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_2),
    .ap_return_3(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_3),
    .ap_return_4(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_4),
    .ap_return_5(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_5),
    .ap_return_6(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_6),
    .ap_return_7(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_7),
    .ap_ext_blocking_n(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_str_blocking_n),
    .ap_int_blocking_n(grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_int_blocking_n)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln151_reg_807_pp0_iter5_reg == 1'd0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_747 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start_reg <= 1'b1;
        end else if ((grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ready == 1'b1)) begin
            grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln151_reg_807 == 1'd1))) begin
        k1_reg_134 <= k_reg_802;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln151_reg_807 == 1'd0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k1_reg_134 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_98_p3 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_of_ns_M_imag_V_0_reg_756 <= {{p_fftInData_reOrdered_dout[58:32]}};
        X_of_ns_M_imag_V_1_reg_767 <= {{p_fftInData_reOrdered_dout[122:96]}};
        X_of_ns_M_imag_V_2_reg_779 <= {{p_fftInData_reOrdered_dout[186:160]}};
        X_of_ns_M_imag_V_3_reg_791 <= {{p_fftInData_reOrdered_dout[250:224]}};
        X_of_ns_M_real_V_0_reg_751 <= X_of_ns_M_real_V_0_fu_180_p1;
        X_of_ns_M_real_V_1_reg_761 <= {{p_fftInData_reOrdered_dout[90:64]}};
        X_of_ns_M_real_V_2_reg_773 <= {{p_fftInData_reOrdered_dout[154:128]}};
        X_of_ns_M_real_V_3_reg_785 <= {{p_fftInData_reOrdered_dout[218:192]}};
        trunc_ln151_reg_797 <= trunc_ln151_fu_254_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_747 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bflyOutData_M_imag_V_0_reg_816 <= bflyOutData_M_imag_V_0_fu_361_p2;
        bflyOutData_M_imag_V_1_reg_826 <= bflyOutData_M_imag_V_1_fu_527_p2;
        bflyOutData_M_imag_V_2_reg_836 <= bflyOutData_M_imag_V_2_fu_616_p2;
        bflyOutData_M_imag_V_3_reg_846 <= bflyOutData_M_imag_V_3_fu_668_p2;
        bflyOutData_M_real_V_0_reg_811 <= bflyOutData_M_real_V_0_fu_347_p2;
        bflyOutData_M_real_V_1_reg_821 <= bflyOutData_M_real_V_1_fu_513_p2;
        bflyOutData_M_real_V_2_reg_831 <= bflyOutData_M_real_V_2_fu_602_p2;
        bflyOutData_M_real_V_3_reg_841 <= bflyOutData_M_real_V_3_fu_654_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln151_reg_807 <= icmp_ln151_fu_274_p2;
        icmp_ln151_reg_807_pp0_iter1_reg <= icmp_ln151_reg_807;
        tmp_reg_747 <= tmp_nbreadreq_fu_98_p3;
        tmp_reg_747_pp0_iter1_reg <= tmp_reg_747;
        trunc_ln151_reg_797_pp0_iter1_reg <= trunc_ln151_reg_797;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln151_reg_807_pp0_iter2_reg <= icmp_ln151_reg_807_pp0_iter1_reg;
        icmp_ln151_reg_807_pp0_iter3_reg <= icmp_ln151_reg_807_pp0_iter2_reg;
        icmp_ln151_reg_807_pp0_iter4_reg <= icmp_ln151_reg_807_pp0_iter3_reg;
        icmp_ln151_reg_807_pp0_iter5_reg <= icmp_ln151_reg_807_pp0_iter4_reg;
        tmp_reg_747_pp0_iter2_reg <= tmp_reg_747_pp0_iter1_reg;
        tmp_reg_747_pp0_iter3_reg <= tmp_reg_747_pp0_iter2_reg;
        tmp_reg_747_pp0_iter4_reg <= tmp_reg_747_pp0_iter3_reg;
        tmp_reg_747_pp0_iter5_reg <= tmp_reg_747_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_reg_802 <= k_fu_258_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln151_reg_807_pp0_iter5_reg == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_ext_blocking_0) == 1'b1)) begin
        ap_ext_blocking_sub_n = 1'b0;
    end else begin
        ap_ext_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_int_blocking_0) == 1'b1)) begin
        ap_int_blocking_sub_n = 1'b0;
    end else begin
        ap_int_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_271)) begin
        if ((icmp_ln151_reg_807 == 1'd0)) begin
            ap_phi_mux_k1_phi_fu_138_p6 = 32'd0;
        end else if ((icmp_ln151_reg_807 == 1'd1)) begin
            ap_phi_mux_k1_phi_fu_138_p6 = k_reg_802;
        end else begin
            ap_phi_mux_k1_phi_fu_138_p6 = k1_reg_134;
        end
    end else begin
        ap_phi_mux_k1_phi_fu_138_p6 = k1_reg_134;
    end
end

always @ (*) begin
    if ((tmp_nbreadreq_fu_98_p3 == 1'd0)) begin
        ap_phi_mux_k_1_phi_fu_151_p4 = k_2_fu_173_p2;
    end else if ((tmp_nbreadreq_fu_98_p3 == 1'd1)) begin
        ap_phi_mux_k_1_phi_fu_151_p4 = ap_phi_mux_k1_phi_fu_138_p6;
    end else begin
        ap_phi_mux_k_1_phi_fu_151_p4 = ap_phi_reg_pp0_iter0_k_1_reg_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (icmp_ln151_fu_274_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to5 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_wait_0 & ap_sub_str_blocking_0) == 1'b1)) begin
        ap_str_blocking_sub_n = 1'b0;
    end else begin
        ap_str_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_0 = 1'b1;
    end else begin
        ap_sub_ext_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_0 = 1'b1;
    end else begin
        ap_sub_int_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_0 = 1'b1;
    end else begin
        ap_sub_str_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm)) begin
        ap_wait_0 = 1'b1;
    end else begin
        ap_wait_0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (tmp_reg_747_pp0_iter5_reg == 1'd1))) begin
        fftOutData_local_blk_n = fftOutData_local_full_n;
    end else begin
        fftOutData_local_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (tmp_reg_747_pp0_iter5_reg == 1'd1))) begin
        fftOutData_local_write = 1'b1;
    end else begin
        fftOutData_local_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp113) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ce = 1'b1;
    end else begin
        grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_nbreadreq_fu_98_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_fftInData_reOrdered_blk_n = p_fftInData_reOrdered_empty_n;
    end else begin
        p_fftInData_reOrdered_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_98_p3 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_fftInData_reOrdered_read = 1'b1;
    end else begin
        p_fftInData_reOrdered_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_of_ns_M_real_V_0_fu_180_p1 = p_fftInData_reOrdered_dout[26:0];

assign add_ln712_12_fu_570_p2 = ($signed(p_val_V_18_fu_390_p4) + $signed(sext_ln717_fu_280_p1));

assign add_ln712_13_fu_576_p2 = ($signed(p_val_V_22_fu_533_p4) + $signed(sext_ln717_1_fu_283_p1));

assign add_ln712_14_fu_582_p2 = ($signed(p_val_V_23_fu_560_p4) + $signed(sext_ln1245_1_fu_318_p1));

assign add_ln712_15_fu_588_p2 = ($signed(p_val_V_21_fu_471_p4) + $signed(sext_ln1245_3_fu_330_p1));

assign add_ln712_18_fu_622_p2 = ($signed(p_val_V_22_fu_533_p4) + $signed(sext_ln717_fu_280_p1));

assign add_ln712_19_fu_628_p2 = ($signed(sext_ln717_2_fu_286_p1) + $signed(sext_ln717_1_fu_283_p1));

assign add_ln712_1_fu_309_p2 = ($signed(sext_ln717_3_fu_300_p1) + $signed(sext_ln717_1_fu_283_p1));

assign add_ln712_20_fu_634_p2 = ($signed(p_val_V_19_fu_417_p4) + $signed(sext_ln1245_2_fu_327_p1));

assign add_ln712_21_fu_640_p2 = (p_val_V_23_fu_560_p4 + p_val_V_20_fu_444_p4);

assign add_ln712_2_fu_321_p2 = ($signed(sext_ln1245_fu_315_p1) + $signed(sext_ln1245_1_fu_318_p1));

assign add_ln712_3_fu_333_p2 = ($signed(sext_ln1245_2_fu_327_p1) + $signed(sext_ln1245_3_fu_330_p1));

assign add_ln712_6_fu_481_p2 = ($signed(sext_ln717_3_fu_300_p1) + $signed(sext_ln717_fu_280_p1));

assign add_ln712_7_fu_487_p2 = ($signed(p_val_V_18_fu_390_p4) + $signed(sext_ln717_1_fu_283_p1));

assign add_ln712_8_fu_493_p2 = (p_val_V_21_fu_471_p4 + p_val_V_19_fu_417_p4);

assign add_ln712_9_fu_499_p2 = ($signed(p_val_V_20_fu_444_p4) + $signed(sext_ln1245_fu_315_p1));

assign add_ln712_fu_303_p2 = ($signed(sext_ln717_2_fu_286_p1) + $signed(sext_ln717_fu_280_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (tmp_reg_747_pp0_iter5_reg == 1'd1) & (fftOutData_local_full_n == 1'b0)) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (p_fftInData_reOrdered_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (tmp_reg_747_pp0_iter5_reg == 1'd1) & (fftOutData_local_full_n == 1'b0)) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (p_fftInData_reOrdered_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp113 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (tmp_reg_747_pp0_iter5_reg == 1'd1) & (fftOutData_local_full_n == 1'b0)) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (p_fftInData_reOrdered_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (tmp_reg_747_pp0_iter5_reg == 1'd1) & (fftOutData_local_full_n == 1'b0)) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (p_fftInData_reOrdered_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (p_fftInData_reOrdered_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0_ignore_call82 = ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (p_fftInData_reOrdered_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1_ignore_call82 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2_ignore_call82 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3_ignore_call82 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4_ignore_call82 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5_ignore_call82 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter6 = ((tmp_reg_747_pp0_iter5_reg == 1'd1) & (fftOutData_local_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter6_ignore_call82 = ((tmp_reg_747_pp0_iter5_reg == 1'd1) & (fftOutData_local_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_271 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & 1'b1);

assign ap_int_blocking_cur_n = (p_fftInData_reOrdered_blk_n & fftOutData_local_blk_n);

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_phi_reg_pp0_iter0_k_1_reg_148 = 'bx;

assign ap_str_blocking_n = (ap_str_blocking_sub_n & 1'b1);

assign bflyOutData_M_imag_V_0_fu_361_p2 = ($signed(sext_ln712_16_fu_353_p1) + $signed(sext_ln712_17_fu_357_p1));

assign bflyOutData_M_imag_V_1_fu_527_p2 = ($signed(sext_ln712_20_fu_519_p1) + $signed(sext_ln712_21_fu_523_p1));

assign bflyOutData_M_imag_V_2_fu_616_p2 = ($signed(sext_ln712_24_fu_608_p1) + $signed(sext_ln712_25_fu_612_p1));

assign bflyOutData_M_imag_V_3_fu_668_p2 = ($signed(sext_ln712_28_fu_660_p1) + $signed(sext_ln712_29_fu_664_p1));

assign bflyOutData_M_real_V_0_fu_347_p2 = ($signed(sext_ln712_fu_339_p1) + $signed(sext_ln712_15_fu_343_p1));

assign bflyOutData_M_real_V_1_fu_513_p2 = ($signed(sext_ln712_18_fu_505_p1) + $signed(sext_ln712_19_fu_509_p1));

assign bflyOutData_M_real_V_2_fu_602_p2 = ($signed(sext_ln712_22_fu_594_p1) + $signed(sext_ln712_23_fu_598_p1));

assign bflyOutData_M_real_V_3_fu_654_p2 = ($signed(sext_ln712_26_fu_646_p1) + $signed(sext_ln712_27_fu_650_p1));

assign fftOutData_local_din = tmp_s_fu_706_p16;

assign grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start = grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_start_reg;

assign icmp_ln151_fu_274_p2 = (($signed(tmp_96_fu_264_p4) < $signed(30'd1)) ? 1'b1 : 1'b0);

assign k_2_fu_173_p2 = ($signed(ap_phi_mux_k1_phi_fu_138_p6) + $signed(32'd4294967295));

assign k_fu_258_p2 = (ap_phi_mux_k_1_phi_fu_151_p4 + 32'd1);

assign p_val_V_18_fu_390_p4 = {{r_V_fu_384_p2[43:16]}};

assign p_val_V_19_fu_417_p4 = {{r_V_29_fu_411_p2[43:16]}};

assign p_val_V_20_fu_444_p4 = {{r_V_30_fu_438_p2[43:16]}};

assign p_val_V_21_fu_471_p4 = {{ret_V_fu_465_p2[43:16]}};

assign p_val_V_22_fu_533_p4 = {{r_V_35_fu_367_p2[43:16]}};

assign p_val_V_23_fu_560_p4 = {{r_V_32_fu_554_p2[43:16]}};

assign r_V_29_fu_411_p2 = ($signed(44'd0) - $signed(sext_ln1171_29_fu_407_p1));

assign r_V_30_fu_438_p2 = ($signed(44'd0) - $signed(sext_ln1171_30_fu_434_p1));

assign r_V_32_fu_554_p2 = ($signed(44'd0) - $signed(sext_ln1171_31_fu_550_p1));

assign r_V_34_fu_289_p3 = {{X_of_ns_M_imag_V_1_reg_767}, {16'd0}};

assign r_V_35_fu_367_p2 = ($signed(44'd0) - $signed(sext_ln1168_fu_296_p1));

assign r_V_36_fu_454_p3 = {{X_of_ns_M_imag_V_3_reg_791}, {16'd0}};

assign r_V_fu_384_p2 = ($signed(44'd0) - $signed(sext_ln1171_fu_380_p1));

assign ret_V_fu_465_p2 = ($signed(44'd0) - $signed(sext_ln1168_1_fu_461_p1));

assign sext_ln1168_1_fu_461_p1 = $signed(r_V_36_fu_454_p3);

assign sext_ln1168_fu_296_p1 = $signed(r_V_34_fu_289_p3);

assign sext_ln1171_29_fu_407_p1 = $signed(shl_ln1171_1_fu_400_p3);

assign sext_ln1171_30_fu_434_p1 = $signed(shl_ln1171_2_fu_427_p3);

assign sext_ln1171_31_fu_550_p1 = $signed(shl_ln1171_4_fu_543_p3);

assign sext_ln1171_fu_380_p1 = $signed(shl_ln_fu_373_p3);

assign sext_ln1245_1_fu_318_p1 = X_of_ns_M_real_V_2_reg_773;

assign sext_ln1245_2_fu_327_p1 = X_of_ns_M_imag_V_3_reg_791;

assign sext_ln1245_3_fu_330_p1 = X_of_ns_M_imag_V_2_reg_779;

assign sext_ln1245_fu_315_p1 = X_of_ns_M_real_V_3_reg_785;

assign sext_ln712_15_fu_343_p1 = $signed(add_ln712_fu_303_p2);

assign sext_ln712_16_fu_353_p1 = $signed(add_ln712_3_fu_333_p2);

assign sext_ln712_17_fu_357_p1 = $signed(add_ln712_1_fu_309_p2);

assign sext_ln712_18_fu_505_p1 = $signed(add_ln712_8_fu_493_p2);

assign sext_ln712_19_fu_509_p1 = $signed(add_ln712_6_fu_481_p2);

assign sext_ln712_20_fu_519_p1 = $signed(add_ln712_9_fu_499_p2);

assign sext_ln712_21_fu_523_p1 = $signed(add_ln712_7_fu_487_p2);

assign sext_ln712_22_fu_594_p1 = $signed(add_ln712_14_fu_582_p2);

assign sext_ln712_23_fu_598_p1 = $signed(add_ln712_12_fu_570_p2);

assign sext_ln712_24_fu_608_p1 = $signed(add_ln712_15_fu_588_p2);

assign sext_ln712_25_fu_612_p1 = $signed(add_ln712_13_fu_576_p2);

assign sext_ln712_26_fu_646_p1 = $signed(add_ln712_20_fu_634_p2);

assign sext_ln712_27_fu_650_p1 = $signed(add_ln712_18_fu_622_p2);

assign sext_ln712_28_fu_660_p1 = $signed(add_ln712_21_fu_640_p2);

assign sext_ln712_29_fu_664_p1 = $signed(add_ln712_19_fu_628_p2);

assign sext_ln712_fu_339_p1 = $signed(add_ln712_2_fu_321_p2);

assign sext_ln717_1_fu_283_p1 = $signed(X_of_ns_M_imag_V_0_reg_756);

assign sext_ln717_2_fu_286_p1 = X_of_ns_M_real_V_1_reg_761;

assign sext_ln717_3_fu_300_p1 = X_of_ns_M_imag_V_1_reg_767;

assign sext_ln717_fu_280_p1 = $signed(X_of_ns_M_real_V_0_reg_751);

assign shl_ln1171_1_fu_400_p3 = {{X_of_ns_M_real_V_2_reg_773}, {16'd0}};

assign shl_ln1171_2_fu_427_p3 = {{X_of_ns_M_imag_V_2_reg_779}, {16'd0}};

assign shl_ln1171_4_fu_543_p3 = {{X_of_ns_M_real_V_3_reg_785}, {16'd0}};

assign shl_ln_fu_373_p3 = {{X_of_ns_M_real_V_1_reg_761}, {16'd0}};

assign tmp_96_fu_264_p4 = {{k_fu_258_p2[31:2]}};

assign tmp_nbreadreq_fu_98_p3 = p_fftInData_reOrdered_empty_n;

assign tmp_s_fu_706_p16 = {{{{{{{{{{{{{{{grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_7}, {2'd0}}, {grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_3}}, {2'd0}}, {grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_6}}, {2'd0}}, {grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_2}}, {2'd0}}, {grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_5}}, {2'd0}}, {grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_1}}, {2'd0}}, {grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_4}}, {2'd0}}, {grp_twiddleFactorMulS2S_16_4_0_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_30_16_5_3_0_s_fu_158_ap_return_0}};

assign trunc_ln151_fu_254_p1 = ap_phi_mux_k1_phi_fu_138_p6[3:0];

endmodule //fft2DKernel_fftStageKernelS2S_16_4_0_0_0_2_complex_ap_fixed_30_16_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_18_2_5_3_0_complex_ap_fixed_27_13_5_3_0_complex_ap_fixed_30_16_5_3_0_87
